// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.txz.log_manager;

@SuppressWarnings("hiding")
public interface LogManager {
  
  // enum SubCommand
  public static final int SUBCMD_DEFAULT = 0;
  public static final int SUBCMD_LOG_STREAM = 1;
  public static final int SUBCMD_LOG_FILE = 2;
  public static final int SUBCMD_LOG_INDEX = 3;
  public static final int SUPCMD_UPLOAD_VOICE_FILE = 4;
  
  // enum ErrorCode
  public static final int EC_LOG_DEFAULT = 0;
  public static final int EC_LOG_NULL = 5001;
  public static final int EC_LOG_GET_DATA_FAIL = 5002;
  public static final int EC_LOG_DATA_TOO_LARGE = 5003;
  public static final int EC_LOG_UPLOADING = 5004;
  public static final int EC_LOG_SEQ_ERROR = 5005;
  public static final int EC_LOG_READ_FILE_ERR = 5006;
  public static final int EC_LOG_FILE_NO_EXIST = 5007;
  
  public static final class Log extends
      com.google.protobuf.nano.MessageNano {
    
    private static volatile Log[] _emptyArray;
    public static Log[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Log[0];
          }
        }
      }
      return _emptyArray;
    }
    
    // optional uint64 uint64_id = 1;
    public java.lang.Long uint64Id;
    
    // optional uint64 uint64_time = 2;
    public java.lang.Long uint64Time;
    
    // optional uint32 uint32_level = 3;
    public java.lang.Integer uint32Level;
    
    // optional string str_tag = 4;
    public java.lang.String strTag;
    
    // optional string str_data = 5;
    public java.lang.String strData;
    
    // optional string str_file = 6;
    public java.lang.String strFile;
    
    // optional uint32 uint32_line = 7;
    public java.lang.Integer uint32Line;
    
    // optional string str_module = 8;
    public java.lang.String strModule;
    
    // optional uint64 uint64_clock = 9;
    public java.lang.Long uint64Clock;
    
    // optional uint32 uint32_pid = 10;
    public java.lang.Integer uint32Pid;
    
    // optional uint64 uint64_tid = 11;
    public java.lang.Long uint64Tid;
    
    public Log() {
      clear();
    }
    
    public Log clear() {
      uint64Id = null;
      uint64Time = null;
      uint32Level = null;
      strTag = null;
      strData = null;
      strFile = null;
      uint32Line = null;
      strModule = null;
      uint64Clock = null;
      uint32Pid = null;
      uint64Tid = null;
      cachedSize = -1;
      return this;
    }
    
    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.uint64Id != null) {
        output.writeUInt64(1, this.uint64Id);
      }
      if (this.uint64Time != null) {
        output.writeUInt64(2, this.uint64Time);
      }
      if (this.uint32Level != null) {
        output.writeUInt32(3, this.uint32Level);
      }
      if (this.strTag != null) {
        output.writeString(4, this.strTag);
      }
      if (this.strData != null) {
        output.writeString(5, this.strData);
      }
      if (this.strFile != null) {
        output.writeString(6, this.strFile);
      }
      if (this.uint32Line != null) {
        output.writeUInt32(7, this.uint32Line);
      }
      if (this.strModule != null) {
        output.writeString(8, this.strModule);
      }
      if (this.uint64Clock != null) {
        output.writeUInt64(9, this.uint64Clock);
      }
      if (this.uint32Pid != null) {
        output.writeUInt32(10, this.uint32Pid);
      }
      if (this.uint64Tid != null) {
        output.writeUInt64(11, this.uint64Tid);
      }
      super.writeTo(output);
    }
    
    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.uint64Id != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt64Size(1, this.uint64Id);
      }
      if (this.uint64Time != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt64Size(2, this.uint64Time);
      }
      if (this.uint32Level != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(3, this.uint32Level);
      }
      if (this.strTag != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(4, this.strTag);
      }
      if (this.strData != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(5, this.strData);
      }
      if (this.strFile != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(6, this.strFile);
      }
      if (this.uint32Line != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(7, this.uint32Line);
      }
      if (this.strModule != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(8, this.strModule);
      }
      if (this.uint64Clock != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt64Size(9, this.uint64Clock);
      }
      if (this.uint32Pid != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(10, this.uint32Pid);
      }
      if (this.uint64Tid != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt64Size(11, this.uint64Tid);
      }
      return size;
    }
    
    @Override
    public Log mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.uint64Id = input.readUInt64();
            break;
          }
          case 16: {
            this.uint64Time = input.readUInt64();
            break;
          }
          case 24: {
            this.uint32Level = input.readUInt32();
            break;
          }
          case 34: {
            this.strTag = input.readString();
            break;
          }
          case 42: {
            this.strData = input.readString();
            break;
          }
          case 50: {
            this.strFile = input.readString();
            break;
          }
          case 56: {
            this.uint32Line = input.readUInt32();
            break;
          }
          case 66: {
            this.strModule = input.readString();
            break;
          }
          case 72: {
            this.uint64Clock = input.readUInt64();
            break;
          }
          case 80: {
            this.uint32Pid = input.readUInt32();
            break;
          }
          case 88: {
            this.uint64Tid = input.readUInt64();
            break;
          }
        }
      }
    }
    
    public static Log parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Log(), data);
    }
    
    public static Log parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Log().mergeFrom(input);
    }
  }
  
  public static final class Req_LogFile extends
      com.google.protobuf.nano.MessageNano {
    
    private static volatile Req_LogFile[] _emptyArray;
    public static Req_LogFile[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Req_LogFile[0];
          }
        }
      }
      return _emptyArray;
    }
    
    // optional uint32 uint32_level = 1;
    public java.lang.Integer uint32Level;
    
    // optional uint64 uint64_begin_time = 2;
    public java.lang.Long uint64BeginTime;
    
    // optional uint64 uint64_end_time = 3;
    public java.lang.Long uint64EndTime;
    
    // optional uint64 uint64_file_size = 4;
    public java.lang.Long uint64FileSize;
    
    // optional bool b_gzip = 5;
    public java.lang.Boolean bGzip;
    
    // optional bytes str_file_data = 6;
    public byte[] strFileData;
    
    // optional uint64 uint64_begin_seq = 7;
    public java.lang.Long uint64BeginSeq;
    
    // optional uint64 uint64_end_seq = 8;
    public java.lang.Long uint64EndSeq;
    
    // optional uint32 uint32_err_code = 9;
    public java.lang.Integer uint32ErrCode;
    
    // optional string str_err_msg = 10;
    public java.lang.String strErrMsg;
    
    // optional uint32 uint32_index_type = 11;
    public java.lang.Integer uint32IndexType;
    
    public Req_LogFile() {
      clear();
    }
    
    public Req_LogFile clear() {
      uint32Level = null;
      uint64BeginTime = null;
      uint64EndTime = null;
      uint64FileSize = null;
      bGzip = null;
      strFileData = null;
      uint64BeginSeq = null;
      uint64EndSeq = null;
      uint32ErrCode = null;
      strErrMsg = null;
      uint32IndexType = null;
      cachedSize = -1;
      return this;
    }
    
    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.uint32Level != null) {
        output.writeUInt32(1, this.uint32Level);
      }
      if (this.uint64BeginTime != null) {
        output.writeUInt64(2, this.uint64BeginTime);
      }
      if (this.uint64EndTime != null) {
        output.writeUInt64(3, this.uint64EndTime);
      }
      if (this.uint64FileSize != null) {
        output.writeUInt64(4, this.uint64FileSize);
      }
      if (this.bGzip != null) {
        output.writeBool(5, this.bGzip);
      }
      if (this.strFileData != null) {
        output.writeBytes(6, this.strFileData);
      }
      if (this.uint64BeginSeq != null) {
        output.writeUInt64(7, this.uint64BeginSeq);
      }
      if (this.uint64EndSeq != null) {
        output.writeUInt64(8, this.uint64EndSeq);
      }
      if (this.uint32ErrCode != null) {
        output.writeUInt32(9, this.uint32ErrCode);
      }
      if (this.strErrMsg != null) {
        output.writeString(10, this.strErrMsg);
      }
      if (this.uint32IndexType != null) {
        output.writeUInt32(11, this.uint32IndexType);
      }
      super.writeTo(output);
    }
    
    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.uint32Level != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(1, this.uint32Level);
      }
      if (this.uint64BeginTime != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt64Size(2, this.uint64BeginTime);
      }
      if (this.uint64EndTime != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt64Size(3, this.uint64EndTime);
      }
      if (this.uint64FileSize != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt64Size(4, this.uint64FileSize);
      }
      if (this.bGzip != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(5, this.bGzip);
      }
      if (this.strFileData != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBytesSize(6, this.strFileData);
      }
      if (this.uint64BeginSeq != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt64Size(7, this.uint64BeginSeq);
      }
      if (this.uint64EndSeq != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt64Size(8, this.uint64EndSeq);
      }
      if (this.uint32ErrCode != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(9, this.uint32ErrCode);
      }
      if (this.strErrMsg != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(10, this.strErrMsg);
      }
      if (this.uint32IndexType != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(11, this.uint32IndexType);
      }
      return size;
    }
    
    @Override
    public Req_LogFile mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.uint32Level = input.readUInt32();
            break;
          }
          case 16: {
            this.uint64BeginTime = input.readUInt64();
            break;
          }
          case 24: {
            this.uint64EndTime = input.readUInt64();
            break;
          }
          case 32: {
            this.uint64FileSize = input.readUInt64();
            break;
          }
          case 40: {
            this.bGzip = input.readBool();
            break;
          }
          case 50: {
            this.strFileData = input.readBytes();
            break;
          }
          case 56: {
            this.uint64BeginSeq = input.readUInt64();
            break;
          }
          case 64: {
            this.uint64EndSeq = input.readUInt64();
            break;
          }
          case 72: {
            this.uint32ErrCode = input.readUInt32();
            break;
          }
          case 82: {
            this.strErrMsg = input.readString();
            break;
          }
          case 88: {
            this.uint32IndexType = input.readUInt32();
            break;
          }
        }
      }
    }
    
    public static Req_LogFile parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Req_LogFile(), data);
    }
    
    public static Req_LogFile parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Req_LogFile().mergeFrom(input);
    }
  }
  
  public static final class Resp_LogFile extends
      com.google.protobuf.nano.MessageNano {
    
    private static volatile Resp_LogFile[] _emptyArray;
    public static Resp_LogFile[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Resp_LogFile[0];
          }
        }
      }
      return _emptyArray;
    }
    
    public Resp_LogFile() {
      clear();
    }
    
    public Resp_LogFile clear() {
      cachedSize = -1;
      return this;
    }
    
    @Override
    public Resp_LogFile mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
        }
      }
    }
    
    public static Resp_LogFile parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Resp_LogFile(), data);
    }
    
    public static Resp_LogFile parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Resp_LogFile().mergeFrom(input);
    }
  }
  
  public static final class LogIndex extends
      com.google.protobuf.nano.MessageNano {
    
    private static volatile LogIndex[] _emptyArray;
    public static LogIndex[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new LogIndex[0];
          }
        }
      }
      return _emptyArray;
    }
    
    // optional uint32 uint32_begin_time = 1;
    public java.lang.Integer uint32BeginTime;
    
    // optional uint64 uint64_begin_seq = 2;
    public java.lang.Long uint64BeginSeq;
    
    // optional uint32 uint32_end_time = 3;
    public java.lang.Integer uint32EndTime;
    
    // optional uint64 uint64_end_seq = 4;
    public java.lang.Long uint64EndSeq;
    
    // optional uint32 uint32_debug_level_size = 5;
    public java.lang.Integer uint32DebugLevelSize;
    
    // optional uint32 uint32_info_level_size = 6;
    public java.lang.Integer uint32InfoLevelSize;
    
    // optional uint32 uint32_warn_level_size = 7;
    public java.lang.Integer uint32WarnLevelSize;
    
    // optional uint32 uint32_error_level_size = 8;
    public java.lang.Integer uint32ErrorLevelSize;
    
    // optional uint32 uint32_fail_level_size = 9;
    public java.lang.Integer uint32FailLevelSize;
    
    // optional bool b_start_flag = 10;
    public java.lang.Boolean bStartFlag;
    
    public LogIndex() {
      clear();
    }
    
    public LogIndex clear() {
      uint32BeginTime = null;
      uint64BeginSeq = null;
      uint32EndTime = null;
      uint64EndSeq = null;
      uint32DebugLevelSize = null;
      uint32InfoLevelSize = null;
      uint32WarnLevelSize = null;
      uint32ErrorLevelSize = null;
      uint32FailLevelSize = null;
      bStartFlag = null;
      cachedSize = -1;
      return this;
    }
    
    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.uint32BeginTime != null) {
        output.writeUInt32(1, this.uint32BeginTime);
      }
      if (this.uint64BeginSeq != null) {
        output.writeUInt64(2, this.uint64BeginSeq);
      }
      if (this.uint32EndTime != null) {
        output.writeUInt32(3, this.uint32EndTime);
      }
      if (this.uint64EndSeq != null) {
        output.writeUInt64(4, this.uint64EndSeq);
      }
      if (this.uint32DebugLevelSize != null) {
        output.writeUInt32(5, this.uint32DebugLevelSize);
      }
      if (this.uint32InfoLevelSize != null) {
        output.writeUInt32(6, this.uint32InfoLevelSize);
      }
      if (this.uint32WarnLevelSize != null) {
        output.writeUInt32(7, this.uint32WarnLevelSize);
      }
      if (this.uint32ErrorLevelSize != null) {
        output.writeUInt32(8, this.uint32ErrorLevelSize);
      }
      if (this.uint32FailLevelSize != null) {
        output.writeUInt32(9, this.uint32FailLevelSize);
      }
      if (this.bStartFlag != null) {
        output.writeBool(10, this.bStartFlag);
      }
      super.writeTo(output);
    }
    
    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.uint32BeginTime != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(1, this.uint32BeginTime);
      }
      if (this.uint64BeginSeq != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt64Size(2, this.uint64BeginSeq);
      }
      if (this.uint32EndTime != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(3, this.uint32EndTime);
      }
      if (this.uint64EndSeq != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt64Size(4, this.uint64EndSeq);
      }
      if (this.uint32DebugLevelSize != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(5, this.uint32DebugLevelSize);
      }
      if (this.uint32InfoLevelSize != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(6, this.uint32InfoLevelSize);
      }
      if (this.uint32WarnLevelSize != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(7, this.uint32WarnLevelSize);
      }
      if (this.uint32ErrorLevelSize != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(8, this.uint32ErrorLevelSize);
      }
      if (this.uint32FailLevelSize != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(9, this.uint32FailLevelSize);
      }
      if (this.bStartFlag != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(10, this.bStartFlag);
      }
      return size;
    }
    
    @Override
    public LogIndex mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.uint32BeginTime = input.readUInt32();
            break;
          }
          case 16: {
            this.uint64BeginSeq = input.readUInt64();
            break;
          }
          case 24: {
            this.uint32EndTime = input.readUInt32();
            break;
          }
          case 32: {
            this.uint64EndSeq = input.readUInt64();
            break;
          }
          case 40: {
            this.uint32DebugLevelSize = input.readUInt32();
            break;
          }
          case 48: {
            this.uint32InfoLevelSize = input.readUInt32();
            break;
          }
          case 56: {
            this.uint32WarnLevelSize = input.readUInt32();
            break;
          }
          case 64: {
            this.uint32ErrorLevelSize = input.readUInt32();
            break;
          }
          case 72: {
            this.uint32FailLevelSize = input.readUInt32();
            break;
          }
          case 80: {
            this.bStartFlag = input.readBool();
            break;
          }
        }
      }
    }
    
    public static LogIndex parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new LogIndex(), data);
    }
    
    public static LogIndex parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new LogIndex().mergeFrom(input);
    }
  }
  
  public static final class Req_LogIndex extends
      com.google.protobuf.nano.MessageNano {
    
    private static volatile Req_LogIndex[] _emptyArray;
    public static Req_LogIndex[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Req_LogIndex[0];
          }
        }
      }
      return _emptyArray;
    }
    
    // repeated .com.txz.log_manager.LogIndex rpt_msg_index_list = 1;
    public com.txz.log_manager.LogManager.LogIndex[] rptMsgIndexList;
    
    public Req_LogIndex() {
      clear();
    }
    
    public Req_LogIndex clear() {
      rptMsgIndexList = com.txz.log_manager.LogManager.LogIndex.emptyArray();
      cachedSize = -1;
      return this;
    }
    
    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.rptMsgIndexList != null && this.rptMsgIndexList.length > 0) {
        for (int i = 0; i < this.rptMsgIndexList.length; i++) {
          com.txz.log_manager.LogManager.LogIndex element = this.rptMsgIndexList[i];
          if (element != null) {
            output.writeMessage(1, element);
          }
        }
      }
      super.writeTo(output);
    }
    
    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.rptMsgIndexList != null && this.rptMsgIndexList.length > 0) {
        for (int i = 0; i < this.rptMsgIndexList.length; i++) {
          com.txz.log_manager.LogManager.LogIndex element = this.rptMsgIndexList[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(1, element);
          }
        }
      }
      return size;
    }
    
    @Override
    public Req_LogIndex mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 10);
            int i = this.rptMsgIndexList == null ? 0 : this.rptMsgIndexList.length;
            com.txz.log_manager.LogManager.LogIndex[] newArray =
                new com.txz.log_manager.LogManager.LogIndex[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.rptMsgIndexList, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new com.txz.log_manager.LogManager.LogIndex();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new com.txz.log_manager.LogManager.LogIndex();
            input.readMessage(newArray[i]);
            this.rptMsgIndexList = newArray;
            break;
          }
        }
      }
    }
    
    public static Req_LogIndex parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Req_LogIndex(), data);
    }
    
    public static Req_LogIndex parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Req_LogIndex().mergeFrom(input);
    }
  }
  
  public static final class Resp_LogIndex extends
      com.google.protobuf.nano.MessageNano {
    
    private static volatile Resp_LogIndex[] _emptyArray;
    public static Resp_LogIndex[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Resp_LogIndex[0];
          }
        }
      }
      return _emptyArray;
    }
    
    public Resp_LogIndex() {
      clear();
    }
    
    public Resp_LogIndex clear() {
      cachedSize = -1;
      return this;
    }
    
    @Override
    public Resp_LogIndex mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
        }
      }
    }
    
    public static Resp_LogIndex parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Resp_LogIndex(), data);
    }
    
    public static Resp_LogIndex parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Resp_LogIndex().mergeFrom(input);
    }
  }
  
  public static final class Req_UploadVoiceFile extends
      com.google.protobuf.nano.MessageNano {
    
    private static volatile Req_UploadVoiceFile[] _emptyArray;
    public static Req_UploadVoiceFile[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Req_UploadVoiceFile[0];
          }
        }
      }
      return _emptyArray;
    }
    
    // optional uint64 uint64_voice_file_id = 1;
    public java.lang.Long uint64VoiceFileId;
    
    // optional bytes str_voice_file_data = 2;
    public byte[] strVoiceFileData;
    
    // optional bool b_gzip = 3;
    public java.lang.Boolean bGzip;
    
    // optional uint32 uint32_err_code = 4;
    public java.lang.Integer uint32ErrCode;
    
    // optional string str_err_msg = 5;
    public java.lang.String strErrMsg;
    
    // repeated .com.txz.log_manager.File_UploadVoiceFile rpt_upload_voice_file = 6;
    public com.txz.log_manager.LogManager.File_UploadVoiceFile[] rptUploadVoiceFile;
    
    public Req_UploadVoiceFile() {
      clear();
    }
    
    public Req_UploadVoiceFile clear() {
      uint64VoiceFileId = null;
      strVoiceFileData = null;
      bGzip = null;
      uint32ErrCode = null;
      strErrMsg = null;
      rptUploadVoiceFile = com.txz.log_manager.LogManager.File_UploadVoiceFile.emptyArray();
      cachedSize = -1;
      return this;
    }
    
    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.uint64VoiceFileId != null) {
        output.writeUInt64(1, this.uint64VoiceFileId);
      }
      if (this.strVoiceFileData != null) {
        output.writeBytes(2, this.strVoiceFileData);
      }
      if (this.bGzip != null) {
        output.writeBool(3, this.bGzip);
      }
      if (this.uint32ErrCode != null) {
        output.writeUInt32(4, this.uint32ErrCode);
      }
      if (this.strErrMsg != null) {
        output.writeString(5, this.strErrMsg);
      }
      if (this.rptUploadVoiceFile != null && this.rptUploadVoiceFile.length > 0) {
        for (int i = 0; i < this.rptUploadVoiceFile.length; i++) {
          com.txz.log_manager.LogManager.File_UploadVoiceFile element = this.rptUploadVoiceFile[i];
          if (element != null) {
            output.writeMessage(6, element);
          }
        }
      }
      super.writeTo(output);
    }
    
    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.uint64VoiceFileId != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt64Size(1, this.uint64VoiceFileId);
      }
      if (this.strVoiceFileData != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBytesSize(2, this.strVoiceFileData);
      }
      if (this.bGzip != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(3, this.bGzip);
      }
      if (this.uint32ErrCode != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(4, this.uint32ErrCode);
      }
      if (this.strErrMsg != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(5, this.strErrMsg);
      }
      if (this.rptUploadVoiceFile != null && this.rptUploadVoiceFile.length > 0) {
        for (int i = 0; i < this.rptUploadVoiceFile.length; i++) {
          com.txz.log_manager.LogManager.File_UploadVoiceFile element = this.rptUploadVoiceFile[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(6, element);
          }
        }
      }
      return size;
    }
    
    @Override
    public Req_UploadVoiceFile mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.uint64VoiceFileId = input.readUInt64();
            break;
          }
          case 18: {
            this.strVoiceFileData = input.readBytes();
            break;
          }
          case 24: {
            this.bGzip = input.readBool();
            break;
          }
          case 32: {
            this.uint32ErrCode = input.readUInt32();
            break;
          }
          case 42: {
            this.strErrMsg = input.readString();
            break;
          }
          case 50: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 50);
            int i = this.rptUploadVoiceFile == null ? 0 : this.rptUploadVoiceFile.length;
            com.txz.log_manager.LogManager.File_UploadVoiceFile[] newArray =
                new com.txz.log_manager.LogManager.File_UploadVoiceFile[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.rptUploadVoiceFile, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new com.txz.log_manager.LogManager.File_UploadVoiceFile();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new com.txz.log_manager.LogManager.File_UploadVoiceFile();
            input.readMessage(newArray[i]);
            this.rptUploadVoiceFile = newArray;
            break;
          }
        }
      }
    }
    
    public static Req_UploadVoiceFile parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Req_UploadVoiceFile(), data);
    }
    
    public static Req_UploadVoiceFile parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Req_UploadVoiceFile().mergeFrom(input);
    }
  }
  
  public static final class Resp_UploadVoiceFile extends
      com.google.protobuf.nano.MessageNano {
    
    private static volatile Resp_UploadVoiceFile[] _emptyArray;
    public static Resp_UploadVoiceFile[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Resp_UploadVoiceFile[0];
          }
        }
      }
      return _emptyArray;
    }
    
    public Resp_UploadVoiceFile() {
      clear();
    }
    
    public Resp_UploadVoiceFile clear() {
      cachedSize = -1;
      return this;
    }
    
    @Override
    public Resp_UploadVoiceFile mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
        }
      }
    }
    
    public static Resp_UploadVoiceFile parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Resp_UploadVoiceFile(), data);
    }
    
    public static Resp_UploadVoiceFile parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Resp_UploadVoiceFile().mergeFrom(input);
    }
  }
  
  public static final class File_UploadVoiceFile extends
      com.google.protobuf.nano.MessageNano {
    
    private static volatile File_UploadVoiceFile[] _emptyArray;
    public static File_UploadVoiceFile[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new File_UploadVoiceFile[0];
          }
        }
      }
      return _emptyArray;
    }
    
    // optional uint64 uint64_voice_file_id = 1;
    public java.lang.Long uint64VoiceFileId;
    
    // optional uint32 uint32_voice_file_type = 2;
    public java.lang.Integer uint32VoiceFileType;
    
    // optional bytes str_voice_file_data = 3;
    public byte[] strVoiceFileData;
    
    // optional bool b_gzip = 4;
    public java.lang.Boolean bGzip;
    
    public File_UploadVoiceFile() {
      clear();
    }
    
    public File_UploadVoiceFile clear() {
      uint64VoiceFileId = null;
      uint32VoiceFileType = null;
      strVoiceFileData = null;
      bGzip = null;
      cachedSize = -1;
      return this;
    }
    
    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.uint64VoiceFileId != null) {
        output.writeUInt64(1, this.uint64VoiceFileId);
      }
      if (this.uint32VoiceFileType != null) {
        output.writeUInt32(2, this.uint32VoiceFileType);
      }
      if (this.strVoiceFileData != null) {
        output.writeBytes(3, this.strVoiceFileData);
      }
      if (this.bGzip != null) {
        output.writeBool(4, this.bGzip);
      }
      super.writeTo(output);
    }
    
    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.uint64VoiceFileId != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt64Size(1, this.uint64VoiceFileId);
      }
      if (this.uint32VoiceFileType != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(2, this.uint32VoiceFileType);
      }
      if (this.strVoiceFileData != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBytesSize(3, this.strVoiceFileData);
      }
      if (this.bGzip != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(4, this.bGzip);
      }
      return size;
    }
    
    @Override
    public File_UploadVoiceFile mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.uint64VoiceFileId = input.readUInt64();
            break;
          }
          case 16: {
            this.uint32VoiceFileType = input.readUInt32();
            break;
          }
          case 26: {
            this.strVoiceFileData = input.readBytes();
            break;
          }
          case 32: {
            this.bGzip = input.readBool();
            break;
          }
        }
      }
    }
    
    public static File_UploadVoiceFile parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new File_UploadVoiceFile(), data);
    }
    
    public static File_UploadVoiceFile parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new File_UploadVoiceFile().mergeFrom(input);
    }
  }
  
  public static final class File_LogIndexRecord extends
      com.google.protobuf.nano.MessageNano {
    
    private static volatile File_LogIndexRecord[] _emptyArray;
    public static File_LogIndexRecord[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new File_LogIndexRecord[0];
          }
        }
      }
      return _emptyArray;
    }
    
    // optional uint64 uint64_time = 1;
    public java.lang.Long uint64Time;
    
    // optional uint32 uint32_file_index = 2;
    public java.lang.Integer uint32FileIndex;
    
    // optional uint64 uint64_offset = 3;
    public java.lang.Long uint64Offset;
    
    // optional uint64 uint64_seq = 4;
    public java.lang.Long uint64Seq;
    
    // optional uint32 uint32_debug_level_size = 5;
    public java.lang.Integer uint32DebugLevelSize;
    
    // optional uint32 uint32_info_level_size = 6;
    public java.lang.Integer uint32InfoLevelSize;
    
    // optional uint32 uint32_warn_level_size = 7;
    public java.lang.Integer uint32WarnLevelSize;
    
    // optional uint32 uint32_error_level_size = 8;
    public java.lang.Integer uint32ErrorLevelSize;
    
    // optional uint32 uint32_fail_level_size = 9;
    public java.lang.Integer uint32FailLevelSize;
    
    // optional bool b_start_flag = 10;
    public java.lang.Boolean bStartFlag;
    
    public File_LogIndexRecord() {
      clear();
    }
    
    public File_LogIndexRecord clear() {
      uint64Time = null;
      uint32FileIndex = null;
      uint64Offset = null;
      uint64Seq = null;
      uint32DebugLevelSize = null;
      uint32InfoLevelSize = null;
      uint32WarnLevelSize = null;
      uint32ErrorLevelSize = null;
      uint32FailLevelSize = null;
      bStartFlag = null;
      cachedSize = -1;
      return this;
    }
    
    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.uint64Time != null) {
        output.writeUInt64(1, this.uint64Time);
      }
      if (this.uint32FileIndex != null) {
        output.writeUInt32(2, this.uint32FileIndex);
      }
      if (this.uint64Offset != null) {
        output.writeUInt64(3, this.uint64Offset);
      }
      if (this.uint64Seq != null) {
        output.writeUInt64(4, this.uint64Seq);
      }
      if (this.uint32DebugLevelSize != null) {
        output.writeUInt32(5, this.uint32DebugLevelSize);
      }
      if (this.uint32InfoLevelSize != null) {
        output.writeUInt32(6, this.uint32InfoLevelSize);
      }
      if (this.uint32WarnLevelSize != null) {
        output.writeUInt32(7, this.uint32WarnLevelSize);
      }
      if (this.uint32ErrorLevelSize != null) {
        output.writeUInt32(8, this.uint32ErrorLevelSize);
      }
      if (this.uint32FailLevelSize != null) {
        output.writeUInt32(9, this.uint32FailLevelSize);
      }
      if (this.bStartFlag != null) {
        output.writeBool(10, this.bStartFlag);
      }
      super.writeTo(output);
    }
    
    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.uint64Time != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt64Size(1, this.uint64Time);
      }
      if (this.uint32FileIndex != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(2, this.uint32FileIndex);
      }
      if (this.uint64Offset != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt64Size(3, this.uint64Offset);
      }
      if (this.uint64Seq != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt64Size(4, this.uint64Seq);
      }
      if (this.uint32DebugLevelSize != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(5, this.uint32DebugLevelSize);
      }
      if (this.uint32InfoLevelSize != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(6, this.uint32InfoLevelSize);
      }
      if (this.uint32WarnLevelSize != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(7, this.uint32WarnLevelSize);
      }
      if (this.uint32ErrorLevelSize != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(8, this.uint32ErrorLevelSize);
      }
      if (this.uint32FailLevelSize != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(9, this.uint32FailLevelSize);
      }
      if (this.bStartFlag != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(10, this.bStartFlag);
      }
      return size;
    }
    
    @Override
    public File_LogIndexRecord mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.uint64Time = input.readUInt64();
            break;
          }
          case 16: {
            this.uint32FileIndex = input.readUInt32();
            break;
          }
          case 24: {
            this.uint64Offset = input.readUInt64();
            break;
          }
          case 32: {
            this.uint64Seq = input.readUInt64();
            break;
          }
          case 40: {
            this.uint32DebugLevelSize = input.readUInt32();
            break;
          }
          case 48: {
            this.uint32InfoLevelSize = input.readUInt32();
            break;
          }
          case 56: {
            this.uint32WarnLevelSize = input.readUInt32();
            break;
          }
          case 64: {
            this.uint32ErrorLevelSize = input.readUInt32();
            break;
          }
          case 72: {
            this.uint32FailLevelSize = input.readUInt32();
            break;
          }
          case 80: {
            this.bStartFlag = input.readBool();
            break;
          }
        }
      }
    }
    
    public static File_LogIndexRecord parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new File_LogIndexRecord(), data);
    }
    
    public static File_LogIndexRecord parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new File_LogIndexRecord().mergeFrom(input);
    }
  }
  
  public static final class File_LogIndex extends
      com.google.protobuf.nano.MessageNano {
    
    private static volatile File_LogIndex[] _emptyArray;
    public static File_LogIndex[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new File_LogIndex[0];
          }
        }
      }
      return _emptyArray;
    }
    
    // repeated .com.txz.log_manager.File_LogIndexRecord rpt_msg_record_All = 1;
    public com.txz.log_manager.LogManager.File_LogIndexRecord[] rptMsgRecordAll;
    
    // optional uint64 uint64_cur_seq = 3;
    public java.lang.Long uint64CurSeq;
    
    public File_LogIndex() {
      clear();
    }
    
    public File_LogIndex clear() {
      rptMsgRecordAll = com.txz.log_manager.LogManager.File_LogIndexRecord.emptyArray();
      uint64CurSeq = null;
      cachedSize = -1;
      return this;
    }
    
    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.rptMsgRecordAll != null && this.rptMsgRecordAll.length > 0) {
        for (int i = 0; i < this.rptMsgRecordAll.length; i++) {
          com.txz.log_manager.LogManager.File_LogIndexRecord element = this.rptMsgRecordAll[i];
          if (element != null) {
            output.writeMessage(1, element);
          }
        }
      }
      if (this.uint64CurSeq != null) {
        output.writeUInt64(3, this.uint64CurSeq);
      }
      super.writeTo(output);
    }
    
    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.rptMsgRecordAll != null && this.rptMsgRecordAll.length > 0) {
        for (int i = 0; i < this.rptMsgRecordAll.length; i++) {
          com.txz.log_manager.LogManager.File_LogIndexRecord element = this.rptMsgRecordAll[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(1, element);
          }
        }
      }
      if (this.uint64CurSeq != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt64Size(3, this.uint64CurSeq);
      }
      return size;
    }
    
    @Override
    public File_LogIndex mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 10);
            int i = this.rptMsgRecordAll == null ? 0 : this.rptMsgRecordAll.length;
            com.txz.log_manager.LogManager.File_LogIndexRecord[] newArray =
                new com.txz.log_manager.LogManager.File_LogIndexRecord[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.rptMsgRecordAll, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new com.txz.log_manager.LogManager.File_LogIndexRecord();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new com.txz.log_manager.LogManager.File_LogIndexRecord();
            input.readMessage(newArray[i]);
            this.rptMsgRecordAll = newArray;
            break;
          }
          case 24: {
            this.uint64CurSeq = input.readUInt64();
            break;
          }
        }
      }
    }
    
    public static File_LogIndex parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new File_LogIndex(), data);
    }
    
    public static File_LogIndex parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new File_LogIndex().mergeFrom(input);
    }
  }
}
