// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.txz.data_manager;

@SuppressWarnings("hiding")
public interface DataManager {
  
  // enum SubCommand
  public static final int SUBCMD_DEFAULT = 0;
  public static final int SUBCMD_UPLOAD_CREATE = 1;
  public static final int SUBCMD_UPLOAD_DATA = 2;
  public static final int SUBCMD_DOWNLOAD_DATA = 3;
  public static final int SUMCMD_UPLOAD_FLOW_DATA = 4;
  public static final int SUBCMD_REPORT_LOCATION = 257;
  public static final int SUBCMD_BIG_UPLOAD_CREATE = 5;
  public static final int SUBCMD_BIG_UPLOAD_DATA = 6;
  
  // enum ErrorCode
  public static final int EC_DEFAULT = 0;
  public static final int EC_UPLOAD_CREATE_ERR = 3001;
  public static final int EC_UPLOAD_NOT_CREATE = 3002;
  public static final int EC_UPLOAD_PIECE_DATA_ERR = 3003;
  public static final int EC_UPLOAD_INDEX_FORMAT_ERR = 3004;
  
  public static final class UploadUserFileInfo extends
      com.google.protobuf.nano.MessageNano {
    
    private static volatile UploadUserFileInfo[] _emptyArray;
    public static UploadUserFileInfo[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new UploadUserFileInfo[0];
          }
        }
      }
      return _emptyArray;
    }
    
    // optional string str_user_file_category = 1;
    public java.lang.String strUserFileCategory;
    
    // optional string str_user_file_name = 2;
    public java.lang.String strUserFileName;
    
    public UploadUserFileInfo() {
      clear();
    }
    
    public UploadUserFileInfo clear() {
      strUserFileCategory = null;
      strUserFileName = null;
      cachedSize = -1;
      return this;
    }
    
    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.strUserFileCategory != null) {
        output.writeString(1, this.strUserFileCategory);
      }
      if (this.strUserFileName != null) {
        output.writeString(2, this.strUserFileName);
      }
      super.writeTo(output);
    }
    
    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.strUserFileCategory != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.strUserFileCategory);
      }
      if (this.strUserFileName != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.strUserFileName);
      }
      return size;
    }
    
    @Override
    public UploadUserFileInfo mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.strUserFileCategory = input.readString();
            break;
          }
          case 18: {
            this.strUserFileName = input.readString();
            break;
          }
        }
      }
    }
    
    public static UploadUserFileInfo parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new UploadUserFileInfo(), data);
    }
    
    public static UploadUserFileInfo parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new UploadUserFileInfo().mergeFrom(input);
    }
  }
  
  public static final class UploadSession extends
      com.google.protobuf.nano.MessageNano {
    
    private static volatile UploadSession[] _emptyArray;
    public static UploadSession[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new UploadSession[0];
          }
        }
      }
      return _emptyArray;
    }
    
    // optional uint64 uint64_uid = 1;
    public java.lang.Long uint64Uid;
    
    // optional uint32 uint32_cmd = 2;
    public java.lang.Integer uint32Cmd;
    
    // optional uint32 uint32_subcmd = 3;
    public java.lang.Integer uint32Subcmd;
    
    // optional uint32 uint32_seq = 4;
    public java.lang.Integer uint32Seq;
    
    // optional uint64 uint64_push_mid = 5;
    public java.lang.Long uint64PushMid;
    
    public UploadSession() {
      clear();
    }
    
    public UploadSession clear() {
      uint64Uid = null;
      uint32Cmd = null;
      uint32Subcmd = null;
      uint32Seq = null;
      uint64PushMid = null;
      cachedSize = -1;
      return this;
    }
    
    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.uint64Uid != null) {
        output.writeUInt64(1, this.uint64Uid);
      }
      if (this.uint32Cmd != null) {
        output.writeUInt32(2, this.uint32Cmd);
      }
      if (this.uint32Subcmd != null) {
        output.writeUInt32(3, this.uint32Subcmd);
      }
      if (this.uint32Seq != null) {
        output.writeUInt32(4, this.uint32Seq);
      }
      if (this.uint64PushMid != null) {
        output.writeUInt64(5, this.uint64PushMid);
      }
      super.writeTo(output);
    }
    
    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.uint64Uid != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt64Size(1, this.uint64Uid);
      }
      if (this.uint32Cmd != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(2, this.uint32Cmd);
      }
      if (this.uint32Subcmd != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(3, this.uint32Subcmd);
      }
      if (this.uint32Seq != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(4, this.uint32Seq);
      }
      if (this.uint64PushMid != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt64Size(5, this.uint64PushMid);
      }
      return size;
    }
    
    @Override
    public UploadSession mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.uint64Uid = input.readUInt64();
            break;
          }
          case 16: {
            this.uint32Cmd = input.readUInt32();
            break;
          }
          case 24: {
            this.uint32Subcmd = input.readUInt32();
            break;
          }
          case 32: {
            this.uint32Seq = input.readUInt32();
            break;
          }
          case 40: {
            this.uint64PushMid = input.readUInt64();
            break;
          }
        }
      }
    }
    
    public static UploadSession parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new UploadSession(), data);
    }
    
    public static UploadSession parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new UploadSession().mergeFrom(input);
    }
  }
  
  public static final class Req_UploadCreate extends
      com.google.protobuf.nano.MessageNano {
    
    private static volatile Req_UploadCreate[] _emptyArray;
    public static Req_UploadCreate[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Req_UploadCreate[0];
          }
        }
      }
      return _emptyArray;
    }
    
    // optional bytes str_data_md5 = 1;
    public byte[] strDataMd5;
    
    // optional uint32 uint32_data_size = 2;
    public java.lang.Integer uint32DataSize;
    
    // optional uint32 uint32_data_piece_cnt = 3;
    public java.lang.Integer uint32DataPieceCnt;
    
    // repeated bytes rpt_str_piece_md5 = 4;
    public byte[][] rptStrPieceMd5;
    
    // optional bool b_gzip_flag = 5;
    public java.lang.Boolean bGzipFlag;
    
    // optional bytes str_bitmap = 6;
    public byte[] strBitmap;
    
    // optional uint32 uint32_timeout = 7;
    public java.lang.Integer uint32Timeout;
    
    // optional bool bool_private = 8;
    public java.lang.Boolean boolPrivate;
    
    // optional .com.txz.data_manager.UploadUserFileInfo msg_user_file_info = 9;
    public com.txz.data_manager.DataManager.UploadUserFileInfo msgUserFileInfo;
    
    // optional .com.txz.data_manager.UploadSession msg_session_info = 10;
    public com.txz.data_manager.DataManager.UploadSession msgSessionInfo;
    
    public Req_UploadCreate() {
      clear();
    }
    
    public Req_UploadCreate clear() {
      strDataMd5 = null;
      uint32DataSize = null;
      uint32DataPieceCnt = null;
      rptStrPieceMd5 = com.google.protobuf.nano.WireFormatNano.EMPTY_BYTES_ARRAY;
      bGzipFlag = null;
      strBitmap = null;
      uint32Timeout = null;
      boolPrivate = null;
      msgUserFileInfo = null;
      msgSessionInfo = null;
      cachedSize = -1;
      return this;
    }
    
    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.strDataMd5 != null) {
        output.writeBytes(1, this.strDataMd5);
      }
      if (this.uint32DataSize != null) {
        output.writeUInt32(2, this.uint32DataSize);
      }
      if (this.uint32DataPieceCnt != null) {
        output.writeUInt32(3, this.uint32DataPieceCnt);
      }
      if (this.rptStrPieceMd5 != null && this.rptStrPieceMd5.length > 0) {
        for (int i = 0; i < this.rptStrPieceMd5.length; i++) {
          byte[] element = this.rptStrPieceMd5[i];
          if (element != null) {
            output.writeBytes(4, element);
          }
        }
      }
      if (this.bGzipFlag != null) {
        output.writeBool(5, this.bGzipFlag);
      }
      if (this.strBitmap != null) {
        output.writeBytes(6, this.strBitmap);
      }
      if (this.uint32Timeout != null) {
        output.writeUInt32(7, this.uint32Timeout);
      }
      if (this.boolPrivate != null) {
        output.writeBool(8, this.boolPrivate);
      }
      if (this.msgUserFileInfo != null) {
        output.writeMessage(9, this.msgUserFileInfo);
      }
      if (this.msgSessionInfo != null) {
        output.writeMessage(10, this.msgSessionInfo);
      }
      super.writeTo(output);
    }
    
    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.strDataMd5 != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBytesSize(1, this.strDataMd5);
      }
      if (this.uint32DataSize != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(2, this.uint32DataSize);
      }
      if (this.uint32DataPieceCnt != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(3, this.uint32DataPieceCnt);
      }
      if (this.rptStrPieceMd5 != null && this.rptStrPieceMd5.length > 0) {
        int dataCount = 0;
        int dataSize = 0;
        for (int i = 0; i < this.rptStrPieceMd5.length; i++) {
          byte[] element = this.rptStrPieceMd5[i];
          if (element != null) {
            dataCount++;
            dataSize += com.google.protobuf.nano.CodedOutputByteBufferNano
                .computeBytesSizeNoTag(element);
          }
        }
        size += dataSize;
        size += 1 * dataCount;
      }
      if (this.bGzipFlag != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(5, this.bGzipFlag);
      }
      if (this.strBitmap != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBytesSize(6, this.strBitmap);
      }
      if (this.uint32Timeout != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(7, this.uint32Timeout);
      }
      if (this.boolPrivate != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(8, this.boolPrivate);
      }
      if (this.msgUserFileInfo != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(9, this.msgUserFileInfo);
      }
      if (this.msgSessionInfo != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(10, this.msgSessionInfo);
      }
      return size;
    }
    
    @Override
    public Req_UploadCreate mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.strDataMd5 = input.readBytes();
            break;
          }
          case 16: {
            this.uint32DataSize = input.readUInt32();
            break;
          }
          case 24: {
            this.uint32DataPieceCnt = input.readUInt32();
            break;
          }
          case 34: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 34);
            int i = this.rptStrPieceMd5 == null ? 0 : this.rptStrPieceMd5.length;
            byte[][] newArray = new byte[i + arrayLength][];
            if (i != 0) {
              java.lang.System.arraycopy(this.rptStrPieceMd5, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = input.readBytes();
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = input.readBytes();
            this.rptStrPieceMd5 = newArray;
            break;
          }
          case 40: {
            this.bGzipFlag = input.readBool();
            break;
          }
          case 50: {
            this.strBitmap = input.readBytes();
            break;
          }
          case 56: {
            this.uint32Timeout = input.readUInt32();
            break;
          }
          case 64: {
            this.boolPrivate = input.readBool();
            break;
          }
          case 74: {
            if (this.msgUserFileInfo == null) {
              this.msgUserFileInfo = new com.txz.data_manager.DataManager.UploadUserFileInfo();
            }
            input.readMessage(this.msgUserFileInfo);
            break;
          }
          case 82: {
            if (this.msgSessionInfo == null) {
              this.msgSessionInfo = new com.txz.data_manager.DataManager.UploadSession();
            }
            input.readMessage(this.msgSessionInfo);
            break;
          }
        }
      }
    }
    
    public static Req_UploadCreate parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Req_UploadCreate(), data);
    }
    
    public static Req_UploadCreate parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Req_UploadCreate().mergeFrom(input);
    }
  }
  
  public static final class Resp_UploadCreate extends
      com.google.protobuf.nano.MessageNano {
    
    private static volatile Resp_UploadCreate[] _emptyArray;
    public static Resp_UploadCreate[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Resp_UploadCreate[0];
          }
        }
      }
      return _emptyArray;
    }
    
    // optional bytes str_data_md5 = 1;
    public byte[] strDataMd5;
    
    // optional bytes str_bitmap = 2;
    public byte[] strBitmap;
    
    // optional bytes str_data_uri = 3;
    public byte[] strDataUri;
    
    public Resp_UploadCreate() {
      clear();
    }
    
    public Resp_UploadCreate clear() {
      strDataMd5 = null;
      strBitmap = null;
      strDataUri = null;
      cachedSize = -1;
      return this;
    }
    
    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.strDataMd5 != null) {
        output.writeBytes(1, this.strDataMd5);
      }
      if (this.strBitmap != null) {
        output.writeBytes(2, this.strBitmap);
      }
      if (this.strDataUri != null) {
        output.writeBytes(3, this.strDataUri);
      }
      super.writeTo(output);
    }
    
    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.strDataMd5 != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBytesSize(1, this.strDataMd5);
      }
      if (this.strBitmap != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBytesSize(2, this.strBitmap);
      }
      if (this.strDataUri != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBytesSize(3, this.strDataUri);
      }
      return size;
    }
    
    @Override
    public Resp_UploadCreate mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.strDataMd5 = input.readBytes();
            break;
          }
          case 18: {
            this.strBitmap = input.readBytes();
            break;
          }
          case 26: {
            this.strDataUri = input.readBytes();
            break;
          }
        }
      }
    }
    
    public static Resp_UploadCreate parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Resp_UploadCreate(), data);
    }
    
    public static Resp_UploadCreate parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Resp_UploadCreate().mergeFrom(input);
    }
  }
  
  public static final class Req_UploadData extends
      com.google.protobuf.nano.MessageNano {
    
    private static volatile Req_UploadData[] _emptyArray;
    public static Req_UploadData[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Req_UploadData[0];
          }
        }
      }
      return _emptyArray;
    }
    
    // optional bytes str_data_md5 = 1;
    public byte[] strDataMd5;
    
    // optional uint32 uint32_piece_id = 2;
    public java.lang.Integer uint32PieceId;
    
    // optional bytes str_piece_md5 = 4;
    public byte[] strPieceMd5;
    
    // optional bytes str_piece_data = 5;
    public byte[] strPieceData;
    
    // optional .com.txz.data_manager.UploadSession msg_session_info = 6;
    public com.txz.data_manager.DataManager.UploadSession msgSessionInfo;
    
    public Req_UploadData() {
      clear();
    }
    
    public Req_UploadData clear() {
      strDataMd5 = null;
      uint32PieceId = null;
      strPieceMd5 = null;
      strPieceData = null;
      msgSessionInfo = null;
      cachedSize = -1;
      return this;
    }
    
    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.strDataMd5 != null) {
        output.writeBytes(1, this.strDataMd5);
      }
      if (this.uint32PieceId != null) {
        output.writeUInt32(2, this.uint32PieceId);
      }
      if (this.strPieceMd5 != null) {
        output.writeBytes(4, this.strPieceMd5);
      }
      if (this.strPieceData != null) {
        output.writeBytes(5, this.strPieceData);
      }
      if (this.msgSessionInfo != null) {
        output.writeMessage(6, this.msgSessionInfo);
      }
      super.writeTo(output);
    }
    
    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.strDataMd5 != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBytesSize(1, this.strDataMd5);
      }
      if (this.uint32PieceId != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(2, this.uint32PieceId);
      }
      if (this.strPieceMd5 != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBytesSize(4, this.strPieceMd5);
      }
      if (this.strPieceData != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBytesSize(5, this.strPieceData);
      }
      if (this.msgSessionInfo != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(6, this.msgSessionInfo);
      }
      return size;
    }
    
    @Override
    public Req_UploadData mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.strDataMd5 = input.readBytes();
            break;
          }
          case 16: {
            this.uint32PieceId = input.readUInt32();
            break;
          }
          case 34: {
            this.strPieceMd5 = input.readBytes();
            break;
          }
          case 42: {
            this.strPieceData = input.readBytes();
            break;
          }
          case 50: {
            if (this.msgSessionInfo == null) {
              this.msgSessionInfo = new com.txz.data_manager.DataManager.UploadSession();
            }
            input.readMessage(this.msgSessionInfo);
            break;
          }
        }
      }
    }
    
    public static Req_UploadData parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Req_UploadData(), data);
    }
    
    public static Req_UploadData parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Req_UploadData().mergeFrom(input);
    }
  }
  
  public static final class Resp_UploadData extends
      com.google.protobuf.nano.MessageNano {
    
    private static volatile Resp_UploadData[] _emptyArray;
    public static Resp_UploadData[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Resp_UploadData[0];
          }
        }
      }
      return _emptyArray;
    }
    
    // optional bytes str_data_md5 = 1;
    public byte[] strDataMd5;
    
    // optional uint32 uint32_piece_id = 2;
    public java.lang.Integer uint32PieceId;
    
    // optional bytes str_piece_md5 = 3;
    public byte[] strPieceMd5;
    
    // optional bytes str_bitmap = 4;
    public byte[] strBitmap;
    
    // optional bytes str_data_uri = 5;
    public byte[] strDataUri;
    
    public Resp_UploadData() {
      clear();
    }
    
    public Resp_UploadData clear() {
      strDataMd5 = null;
      uint32PieceId = null;
      strPieceMd5 = null;
      strBitmap = null;
      strDataUri = null;
      cachedSize = -1;
      return this;
    }
    
    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.strDataMd5 != null) {
        output.writeBytes(1, this.strDataMd5);
      }
      if (this.uint32PieceId != null) {
        output.writeUInt32(2, this.uint32PieceId);
      }
      if (this.strPieceMd5 != null) {
        output.writeBytes(3, this.strPieceMd5);
      }
      if (this.strBitmap != null) {
        output.writeBytes(4, this.strBitmap);
      }
      if (this.strDataUri != null) {
        output.writeBytes(5, this.strDataUri);
      }
      super.writeTo(output);
    }
    
    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.strDataMd5 != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBytesSize(1, this.strDataMd5);
      }
      if (this.uint32PieceId != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(2, this.uint32PieceId);
      }
      if (this.strPieceMd5 != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBytesSize(3, this.strPieceMd5);
      }
      if (this.strBitmap != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBytesSize(4, this.strBitmap);
      }
      if (this.strDataUri != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBytesSize(5, this.strDataUri);
      }
      return size;
    }
    
    @Override
    public Resp_UploadData mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.strDataMd5 = input.readBytes();
            break;
          }
          case 16: {
            this.uint32PieceId = input.readUInt32();
            break;
          }
          case 26: {
            this.strPieceMd5 = input.readBytes();
            break;
          }
          case 34: {
            this.strBitmap = input.readBytes();
            break;
          }
          case 42: {
            this.strDataUri = input.readBytes();
            break;
          }
        }
      }
    }
    
    public static Resp_UploadData parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Resp_UploadData(), data);
    }
    
    public static Resp_UploadData parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Resp_UploadData().mergeFrom(input);
    }
  }
  
  public static final class Req_BigUploadCreate extends
      com.google.protobuf.nano.MessageNano {
    
    private static volatile Req_BigUploadCreate[] _emptyArray;
    public static Req_BigUploadCreate[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Req_BigUploadCreate[0];
          }
        }
      }
      return _emptyArray;
    }
    
    // optional bytes str_data_md5 = 1;
    public byte[] strDataMd5;
    
    // optional uint32 uint32_data_size = 2;
    public java.lang.Integer uint32DataSize;
    
    // optional uint32 uint32_data_piece_cnt = 3;
    public java.lang.Integer uint32DataPieceCnt;
    
    // repeated bytes rpt_str_piece_md5 = 4;
    public byte[][] rptStrPieceMd5;
    
    // optional bool b_gzip_flag = 5;
    public java.lang.Boolean bGzipFlag;
    
    // optional bytes str_bitmap = 6;
    public byte[] strBitmap;
    
    // optional uint32 uint32_timeout = 7;
    public java.lang.Integer uint32Timeout;
    
    // optional bool bool_private = 8;
    public java.lang.Boolean boolPrivate;
    
    // optional .com.txz.data_manager.UploadUserFileInfo msg_user_file_info = 9;
    public com.txz.data_manager.DataManager.UploadUserFileInfo msgUserFileInfo;
    
    // optional .com.txz.data_manager.UploadSession msg_session_info = 10;
    public com.txz.data_manager.DataManager.UploadSession msgSessionInfo;
    
    public Req_BigUploadCreate() {
      clear();
    }
    
    public Req_BigUploadCreate clear() {
      strDataMd5 = null;
      uint32DataSize = null;
      uint32DataPieceCnt = null;
      rptStrPieceMd5 = com.google.protobuf.nano.WireFormatNano.EMPTY_BYTES_ARRAY;
      bGzipFlag = null;
      strBitmap = null;
      uint32Timeout = null;
      boolPrivate = null;
      msgUserFileInfo = null;
      msgSessionInfo = null;
      cachedSize = -1;
      return this;
    }
    
    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.strDataMd5 != null) {
        output.writeBytes(1, this.strDataMd5);
      }
      if (this.uint32DataSize != null) {
        output.writeUInt32(2, this.uint32DataSize);
      }
      if (this.uint32DataPieceCnt != null) {
        output.writeUInt32(3, this.uint32DataPieceCnt);
      }
      if (this.rptStrPieceMd5 != null && this.rptStrPieceMd5.length > 0) {
        for (int i = 0; i < this.rptStrPieceMd5.length; i++) {
          byte[] element = this.rptStrPieceMd5[i];
          if (element != null) {
            output.writeBytes(4, element);
          }
        }
      }
      if (this.bGzipFlag != null) {
        output.writeBool(5, this.bGzipFlag);
      }
      if (this.strBitmap != null) {
        output.writeBytes(6, this.strBitmap);
      }
      if (this.uint32Timeout != null) {
        output.writeUInt32(7, this.uint32Timeout);
      }
      if (this.boolPrivate != null) {
        output.writeBool(8, this.boolPrivate);
      }
      if (this.msgUserFileInfo != null) {
        output.writeMessage(9, this.msgUserFileInfo);
      }
      if (this.msgSessionInfo != null) {
        output.writeMessage(10, this.msgSessionInfo);
      }
      super.writeTo(output);
    }
    
    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.strDataMd5 != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBytesSize(1, this.strDataMd5);
      }
      if (this.uint32DataSize != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(2, this.uint32DataSize);
      }
      if (this.uint32DataPieceCnt != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(3, this.uint32DataPieceCnt);
      }
      if (this.rptStrPieceMd5 != null && this.rptStrPieceMd5.length > 0) {
        int dataCount = 0;
        int dataSize = 0;
        for (int i = 0; i < this.rptStrPieceMd5.length; i++) {
          byte[] element = this.rptStrPieceMd5[i];
          if (element != null) {
            dataCount++;
            dataSize += com.google.protobuf.nano.CodedOutputByteBufferNano
                .computeBytesSizeNoTag(element);
          }
        }
        size += dataSize;
        size += 1 * dataCount;
      }
      if (this.bGzipFlag != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(5, this.bGzipFlag);
      }
      if (this.strBitmap != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBytesSize(6, this.strBitmap);
      }
      if (this.uint32Timeout != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(7, this.uint32Timeout);
      }
      if (this.boolPrivate != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(8, this.boolPrivate);
      }
      if (this.msgUserFileInfo != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(9, this.msgUserFileInfo);
      }
      if (this.msgSessionInfo != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(10, this.msgSessionInfo);
      }
      return size;
    }
    
    @Override
    public Req_BigUploadCreate mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.strDataMd5 = input.readBytes();
            break;
          }
          case 16: {
            this.uint32DataSize = input.readUInt32();
            break;
          }
          case 24: {
            this.uint32DataPieceCnt = input.readUInt32();
            break;
          }
          case 34: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 34);
            int i = this.rptStrPieceMd5 == null ? 0 : this.rptStrPieceMd5.length;
            byte[][] newArray = new byte[i + arrayLength][];
            if (i != 0) {
              java.lang.System.arraycopy(this.rptStrPieceMd5, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = input.readBytes();
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = input.readBytes();
            this.rptStrPieceMd5 = newArray;
            break;
          }
          case 40: {
            this.bGzipFlag = input.readBool();
            break;
          }
          case 50: {
            this.strBitmap = input.readBytes();
            break;
          }
          case 56: {
            this.uint32Timeout = input.readUInt32();
            break;
          }
          case 64: {
            this.boolPrivate = input.readBool();
            break;
          }
          case 74: {
            if (this.msgUserFileInfo == null) {
              this.msgUserFileInfo = new com.txz.data_manager.DataManager.UploadUserFileInfo();
            }
            input.readMessage(this.msgUserFileInfo);
            break;
          }
          case 82: {
            if (this.msgSessionInfo == null) {
              this.msgSessionInfo = new com.txz.data_manager.DataManager.UploadSession();
            }
            input.readMessage(this.msgSessionInfo);
            break;
          }
        }
      }
    }
    
    public static Req_BigUploadCreate parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Req_BigUploadCreate(), data);
    }
    
    public static Req_BigUploadCreate parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Req_BigUploadCreate().mergeFrom(input);
    }
  }
  
  public static final class Resp_BigUploadCreate extends
      com.google.protobuf.nano.MessageNano {
    
    private static volatile Resp_BigUploadCreate[] _emptyArray;
    public static Resp_BigUploadCreate[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Resp_BigUploadCreate[0];
          }
        }
      }
      return _emptyArray;
    }
    
    // optional bytes str_data_md5 = 1;
    public byte[] strDataMd5;
    
    // optional bytes str_bitmap = 2;
    public byte[] strBitmap;
    
    // optional bytes str_data_uri = 3;
    public byte[] strDataUri;
    
    public Resp_BigUploadCreate() {
      clear();
    }
    
    public Resp_BigUploadCreate clear() {
      strDataMd5 = null;
      strBitmap = null;
      strDataUri = null;
      cachedSize = -1;
      return this;
    }
    
    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.strDataMd5 != null) {
        output.writeBytes(1, this.strDataMd5);
      }
      if (this.strBitmap != null) {
        output.writeBytes(2, this.strBitmap);
      }
      if (this.strDataUri != null) {
        output.writeBytes(3, this.strDataUri);
      }
      super.writeTo(output);
    }
    
    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.strDataMd5 != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBytesSize(1, this.strDataMd5);
      }
      if (this.strBitmap != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBytesSize(2, this.strBitmap);
      }
      if (this.strDataUri != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBytesSize(3, this.strDataUri);
      }
      return size;
    }
    
    @Override
    public Resp_BigUploadCreate mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.strDataMd5 = input.readBytes();
            break;
          }
          case 18: {
            this.strBitmap = input.readBytes();
            break;
          }
          case 26: {
            this.strDataUri = input.readBytes();
            break;
          }
        }
      }
    }
    
    public static Resp_BigUploadCreate parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Resp_BigUploadCreate(), data);
    }
    
    public static Resp_BigUploadCreate parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Resp_BigUploadCreate().mergeFrom(input);
    }
  }
  
  public static final class Req_BigUploadData extends
      com.google.protobuf.nano.MessageNano {
    
    private static volatile Req_BigUploadData[] _emptyArray;
    public static Req_BigUploadData[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Req_BigUploadData[0];
          }
        }
      }
      return _emptyArray;
    }
    
    // optional bytes str_data_md5 = 1;
    public byte[] strDataMd5;
    
    // optional uint32 uint32_piece_id = 2;
    public java.lang.Integer uint32PieceId;
    
    // optional bytes str_piece_md5 = 4;
    public byte[] strPieceMd5;
    
    // optional bytes str_piece_data = 5;
    public byte[] strPieceData;
    
    // optional .com.txz.data_manager.UploadSession msg_session_info = 6;
    public com.txz.data_manager.DataManager.UploadSession msgSessionInfo;
    
    public Req_BigUploadData() {
      clear();
    }
    
    public Req_BigUploadData clear() {
      strDataMd5 = null;
      uint32PieceId = null;
      strPieceMd5 = null;
      strPieceData = null;
      msgSessionInfo = null;
      cachedSize = -1;
      return this;
    }
    
    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.strDataMd5 != null) {
        output.writeBytes(1, this.strDataMd5);
      }
      if (this.uint32PieceId != null) {
        output.writeUInt32(2, this.uint32PieceId);
      }
      if (this.strPieceMd5 != null) {
        output.writeBytes(4, this.strPieceMd5);
      }
      if (this.strPieceData != null) {
        output.writeBytes(5, this.strPieceData);
      }
      if (this.msgSessionInfo != null) {
        output.writeMessage(6, this.msgSessionInfo);
      }
      super.writeTo(output);
    }
    
    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.strDataMd5 != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBytesSize(1, this.strDataMd5);
      }
      if (this.uint32PieceId != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(2, this.uint32PieceId);
      }
      if (this.strPieceMd5 != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBytesSize(4, this.strPieceMd5);
      }
      if (this.strPieceData != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBytesSize(5, this.strPieceData);
      }
      if (this.msgSessionInfo != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(6, this.msgSessionInfo);
      }
      return size;
    }
    
    @Override
    public Req_BigUploadData mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.strDataMd5 = input.readBytes();
            break;
          }
          case 16: {
            this.uint32PieceId = input.readUInt32();
            break;
          }
          case 34: {
            this.strPieceMd5 = input.readBytes();
            break;
          }
          case 42: {
            this.strPieceData = input.readBytes();
            break;
          }
          case 50: {
            if (this.msgSessionInfo == null) {
              this.msgSessionInfo = new com.txz.data_manager.DataManager.UploadSession();
            }
            input.readMessage(this.msgSessionInfo);
            break;
          }
        }
      }
    }
    
    public static Req_BigUploadData parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Req_BigUploadData(), data);
    }
    
    public static Req_BigUploadData parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Req_BigUploadData().mergeFrom(input);
    }
  }
  
  public static final class Resp_BigUploadData extends
      com.google.protobuf.nano.MessageNano {
    
    private static volatile Resp_BigUploadData[] _emptyArray;
    public static Resp_BigUploadData[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Resp_BigUploadData[0];
          }
        }
      }
      return _emptyArray;
    }
    
    // optional bytes str_data_md5 = 1;
    public byte[] strDataMd5;
    
    // optional uint32 uint32_piece_id = 2;
    public java.lang.Integer uint32PieceId;
    
    // optional bytes str_piece_md5 = 3;
    public byte[] strPieceMd5;
    
    // optional bytes str_bitmap = 4;
    public byte[] strBitmap;
    
    // optional bytes str_data_uri = 5;
    public byte[] strDataUri;
    
    // optional bool b_need_package = 6;
    public java.lang.Boolean bNeedPackage;
    
    public Resp_BigUploadData() {
      clear();
    }
    
    public Resp_BigUploadData clear() {
      strDataMd5 = null;
      uint32PieceId = null;
      strPieceMd5 = null;
      strBitmap = null;
      strDataUri = null;
      bNeedPackage = null;
      cachedSize = -1;
      return this;
    }
    
    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.strDataMd5 != null) {
        output.writeBytes(1, this.strDataMd5);
      }
      if (this.uint32PieceId != null) {
        output.writeUInt32(2, this.uint32PieceId);
      }
      if (this.strPieceMd5 != null) {
        output.writeBytes(3, this.strPieceMd5);
      }
      if (this.strBitmap != null) {
        output.writeBytes(4, this.strBitmap);
      }
      if (this.strDataUri != null) {
        output.writeBytes(5, this.strDataUri);
      }
      if (this.bNeedPackage != null) {
        output.writeBool(6, this.bNeedPackage);
      }
      super.writeTo(output);
    }
    
    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.strDataMd5 != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBytesSize(1, this.strDataMd5);
      }
      if (this.uint32PieceId != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(2, this.uint32PieceId);
      }
      if (this.strPieceMd5 != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBytesSize(3, this.strPieceMd5);
      }
      if (this.strBitmap != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBytesSize(4, this.strBitmap);
      }
      if (this.strDataUri != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBytesSize(5, this.strDataUri);
      }
      if (this.bNeedPackage != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(6, this.bNeedPackage);
      }
      return size;
    }
    
    @Override
    public Resp_BigUploadData mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.strDataMd5 = input.readBytes();
            break;
          }
          case 16: {
            this.uint32PieceId = input.readUInt32();
            break;
          }
          case 26: {
            this.strPieceMd5 = input.readBytes();
            break;
          }
          case 34: {
            this.strBitmap = input.readBytes();
            break;
          }
          case 42: {
            this.strDataUri = input.readBytes();
            break;
          }
          case 48: {
            this.bNeedPackage = input.readBool();
            break;
          }
        }
      }
    }
    
    public static Resp_BigUploadData parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Resp_BigUploadData(), data);
    }
    
    public static Resp_BigUploadData parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Resp_BigUploadData().mergeFrom(input);
    }
  }
  
  public static final class Req_DownloadData extends
      com.google.protobuf.nano.MessageNano {
    
    private static volatile Req_DownloadData[] _emptyArray;
    public static Req_DownloadData[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Req_DownloadData[0];
          }
        }
      }
      return _emptyArray;
    }
    
    // optional bytes str_data_id = 1;
    public byte[] strDataId;
    
    // optional uint32 uint32_offset = 2;
    public java.lang.Integer uint32Offset;
    
    // optional uint32 uint32_size = 3;
    public java.lang.Integer uint32Size;
    
    public Req_DownloadData() {
      clear();
    }
    
    public Req_DownloadData clear() {
      strDataId = null;
      uint32Offset = null;
      uint32Size = null;
      cachedSize = -1;
      return this;
    }
    
    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.strDataId != null) {
        output.writeBytes(1, this.strDataId);
      }
      if (this.uint32Offset != null) {
        output.writeUInt32(2, this.uint32Offset);
      }
      if (this.uint32Size != null) {
        output.writeUInt32(3, this.uint32Size);
      }
      super.writeTo(output);
    }
    
    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.strDataId != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBytesSize(1, this.strDataId);
      }
      if (this.uint32Offset != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(2, this.uint32Offset);
      }
      if (this.uint32Size != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(3, this.uint32Size);
      }
      return size;
    }
    
    @Override
    public Req_DownloadData mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.strDataId = input.readBytes();
            break;
          }
          case 16: {
            this.uint32Offset = input.readUInt32();
            break;
          }
          case 24: {
            this.uint32Size = input.readUInt32();
            break;
          }
        }
      }
    }
    
    public static Req_DownloadData parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Req_DownloadData(), data);
    }
    
    public static Req_DownloadData parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Req_DownloadData().mergeFrom(input);
    }
  }
  
  public static final class Resp_DownloadData extends
      com.google.protobuf.nano.MessageNano {
    
    private static volatile Resp_DownloadData[] _emptyArray;
    public static Resp_DownloadData[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Resp_DownloadData[0];
          }
        }
      }
      return _emptyArray;
    }
    
    // optional bytes str_data_id = 1;
    public byte[] strDataId;
    
    // optional uint32 uint32_offset = 2;
    public java.lang.Integer uint32Offset;
    
    // optional uint32 uint32_size = 3;
    public java.lang.Integer uint32Size;
    
    // optional uint32 uint32_total_size = 4;
    public java.lang.Integer uint32TotalSize;
    
    // optional bytes str_data = 5;
    public byte[] strData;
    
    public Resp_DownloadData() {
      clear();
    }
    
    public Resp_DownloadData clear() {
      strDataId = null;
      uint32Offset = null;
      uint32Size = null;
      uint32TotalSize = null;
      strData = null;
      cachedSize = -1;
      return this;
    }
    
    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.strDataId != null) {
        output.writeBytes(1, this.strDataId);
      }
      if (this.uint32Offset != null) {
        output.writeUInt32(2, this.uint32Offset);
      }
      if (this.uint32Size != null) {
        output.writeUInt32(3, this.uint32Size);
      }
      if (this.uint32TotalSize != null) {
        output.writeUInt32(4, this.uint32TotalSize);
      }
      if (this.strData != null) {
        output.writeBytes(5, this.strData);
      }
      super.writeTo(output);
    }
    
    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.strDataId != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBytesSize(1, this.strDataId);
      }
      if (this.uint32Offset != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(2, this.uint32Offset);
      }
      if (this.uint32Size != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(3, this.uint32Size);
      }
      if (this.uint32TotalSize != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(4, this.uint32TotalSize);
      }
      if (this.strData != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBytesSize(5, this.strData);
      }
      return size;
    }
    
    @Override
    public Resp_DownloadData mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.strDataId = input.readBytes();
            break;
          }
          case 16: {
            this.uint32Offset = input.readUInt32();
            break;
          }
          case 24: {
            this.uint32Size = input.readUInt32();
            break;
          }
          case 32: {
            this.uint32TotalSize = input.readUInt32();
            break;
          }
          case 42: {
            this.strData = input.readBytes();
            break;
          }
        }
      }
    }
    
    public static Resp_DownloadData parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Resp_DownloadData(), data);
    }
    
    public static Resp_DownloadData parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Resp_DownloadData().mergeFrom(input);
    }
  }
  
  public static final class Req_UploadFlowData extends
      com.google.protobuf.nano.MessageNano {
    
    private static volatile Req_UploadFlowData[] _emptyArray;
    public static Req_UploadFlowData[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Req_UploadFlowData[0];
          }
        }
      }
      return _emptyArray;
    }
    
    // optional bytes str_data_id = 1;
    public byte[] strDataId;
    
    // optional bool b_finish = 2;
    public java.lang.Boolean bFinish;
    
    // optional uint32 offset = 3;
    public java.lang.Integer offset;
    
    // optional bool b_gzip_flag = 4;
    public java.lang.Boolean bGzipFlag;
    
    // optional bytes str_cur_md5 = 5;
    public byte[] strCurMd5;
    
    // optional bytes str_cur_data = 6;
    public byte[] strCurData;
    
    // optional uint32 uint32_timeout = 7;
    public java.lang.Integer uint32Timeout;
    
    public Req_UploadFlowData() {
      clear();
    }
    
    public Req_UploadFlowData clear() {
      strDataId = null;
      bFinish = null;
      offset = null;
      bGzipFlag = null;
      strCurMd5 = null;
      strCurData = null;
      uint32Timeout = null;
      cachedSize = -1;
      return this;
    }
    
    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.strDataId != null) {
        output.writeBytes(1, this.strDataId);
      }
      if (this.bFinish != null) {
        output.writeBool(2, this.bFinish);
      }
      if (this.offset != null) {
        output.writeUInt32(3, this.offset);
      }
      if (this.bGzipFlag != null) {
        output.writeBool(4, this.bGzipFlag);
      }
      if (this.strCurMd5 != null) {
        output.writeBytes(5, this.strCurMd5);
      }
      if (this.strCurData != null) {
        output.writeBytes(6, this.strCurData);
      }
      if (this.uint32Timeout != null) {
        output.writeUInt32(7, this.uint32Timeout);
      }
      super.writeTo(output);
    }
    
    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.strDataId != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBytesSize(1, this.strDataId);
      }
      if (this.bFinish != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(2, this.bFinish);
      }
      if (this.offset != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(3, this.offset);
      }
      if (this.bGzipFlag != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(4, this.bGzipFlag);
      }
      if (this.strCurMd5 != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBytesSize(5, this.strCurMd5);
      }
      if (this.strCurData != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBytesSize(6, this.strCurData);
      }
      if (this.uint32Timeout != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(7, this.uint32Timeout);
      }
      return size;
    }
    
    @Override
    public Req_UploadFlowData mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.strDataId = input.readBytes();
            break;
          }
          case 16: {
            this.bFinish = input.readBool();
            break;
          }
          case 24: {
            this.offset = input.readUInt32();
            break;
          }
          case 32: {
            this.bGzipFlag = input.readBool();
            break;
          }
          case 42: {
            this.strCurMd5 = input.readBytes();
            break;
          }
          case 50: {
            this.strCurData = input.readBytes();
            break;
          }
          case 56: {
            this.uint32Timeout = input.readUInt32();
            break;
          }
        }
      }
    }
    
    public static Req_UploadFlowData parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Req_UploadFlowData(), data);
    }
    
    public static Req_UploadFlowData parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Req_UploadFlowData().mergeFrom(input);
    }
  }
  
  public static final class Resp_UploadFlowData extends
      com.google.protobuf.nano.MessageNano {
    
    private static volatile Resp_UploadFlowData[] _emptyArray;
    public static Resp_UploadFlowData[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Resp_UploadFlowData[0];
          }
        }
      }
      return _emptyArray;
    }
    
    // optional bytes str_data_id = 1;
    public byte[] strDataId;
    
    // optional uint32 uint32_offset = 2;
    public java.lang.Integer uint32Offset;
    
    // optional bytes str_data_uri = 3;
    public byte[] strDataUri;
    
    public Resp_UploadFlowData() {
      clear();
    }
    
    public Resp_UploadFlowData clear() {
      strDataId = null;
      uint32Offset = null;
      strDataUri = null;
      cachedSize = -1;
      return this;
    }
    
    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.strDataId != null) {
        output.writeBytes(1, this.strDataId);
      }
      if (this.uint32Offset != null) {
        output.writeUInt32(2, this.uint32Offset);
      }
      if (this.strDataUri != null) {
        output.writeBytes(3, this.strDataUri);
      }
      super.writeTo(output);
    }
    
    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.strDataId != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBytesSize(1, this.strDataId);
      }
      if (this.uint32Offset != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(2, this.uint32Offset);
      }
      if (this.strDataUri != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBytesSize(3, this.strDataUri);
      }
      return size;
    }
    
    @Override
    public Resp_UploadFlowData mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.strDataId = input.readBytes();
            break;
          }
          case 16: {
            this.uint32Offset = input.readUInt32();
            break;
          }
          case 26: {
            this.strDataUri = input.readBytes();
            break;
          }
        }
      }
    }
    
    public static Resp_UploadFlowData parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Resp_UploadFlowData(), data);
    }
    
    public static Resp_UploadFlowData parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Resp_UploadFlowData().mergeFrom(input);
    }
  }
}
