package com.txznet.proxy;

import static com.txznet.comm.err.Error.ERROR_CODE_MASK;

public interface ErrCode {
    /**
     * 来源于播放器模块
     */
    int SOURCE_PROXY = 2;

    int ERROR_CLIENT_MEDIA_ERR_IO = SOURCE_PROXY * ERROR_CODE_MASK + 100;
    int ERROR_CLIENT_MEDIA_BAD_DATA = SOURCE_PROXY * ERROR_CODE_MASK + 101;
    int ERROR_CLIENT_MEDIA_FILE_CHECK_FAIL = SOURCE_PROXY * ERROR_CODE_MASK + 102; //文件校验失败
    int ERROR_CLIENT_MEDIA_NOT_FOUND = SOURCE_PROXY * ERROR_CODE_MASK + 103;//请求路径发生404错误
    int ERROR_CLIENT_MEDIA_WRONG_URL = SOURCE_PROXY * ERROR_CODE_MASK + 104; //播放地址错误
    int ERROR_CLIENT_MEDIA_CACHE_SIZE_LIMIT = SOURCE_PROXY * ERROR_CODE_MASK + 105; // 缓存已达上限
    int ERROR_CLIENT_MEDIA_DISK_SPACE_INSUFFICIENT = SOURCE_PROXY * ERROR_CODE_MASK + 106; // 磁盘空间不足
    int ERROR_CLIENT_MEDIA_URL_CHANGE = SOURCE_PROXY * ERROR_CODE_MASK + 107; //文件在播放的过程中路径发生变化

    int ERROR_CLIENT_MEDIA_BAD_REQUEST = SOURCE_PROXY * ERROR_CODE_MASK + 108; //请求路径发生400错误
    int ERROR_CLIENT_MEDIA_FILE_FORBIDDEN = SOURCE_PROXY * ERROR_CODE_MASK + 109; //请求路径发生403错误

}