// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.txz.ui.domain;

@SuppressWarnings("hiding")
public interface UiDomain {
  
  // enum SubEventId
  public static final int SUBEVENT_DEFAULT = 0;
  public static final int SUBEVENT_DOMAIN_PARSE = 1;
  public static final int SUBEVENT_DOMAIN_REPORT = 2;
  
  public static final class Domain extends
      com.google.protobuf.nano.MessageNano {
    
    private static volatile Domain[] _emptyArray;
    public static Domain[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Domain[0];
          }
        }
      }
      return _emptyArray;
    }
    
    // optional bytes str_domain = 1;
    public byte[] strDomain;
    
    // repeated bytes rpt_str_ip = 2;
    public byte[][] rptStrIp;
    
    public Domain() {
      clear();
    }
    
    public Domain clear() {
      strDomain = null;
      rptStrIp = com.google.protobuf.nano.WireFormatNano.EMPTY_BYTES_ARRAY;
      cachedSize = -1;
      return this;
    }
    
    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.strDomain != null) {
        output.writeBytes(1, this.strDomain);
      }
      if (this.rptStrIp != null && this.rptStrIp.length > 0) {
        for (int i = 0; i < this.rptStrIp.length; i++) {
          byte[] element = this.rptStrIp[i];
          if (element != null) {
            output.writeBytes(2, element);
          }
        }
      }
      super.writeTo(output);
    }
    
    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.strDomain != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBytesSize(1, this.strDomain);
      }
      if (this.rptStrIp != null && this.rptStrIp.length > 0) {
        int dataCount = 0;
        int dataSize = 0;
        for (int i = 0; i < this.rptStrIp.length; i++) {
          byte[] element = this.rptStrIp[i];
          if (element != null) {
            dataCount++;
            dataSize += com.google.protobuf.nano.CodedOutputByteBufferNano
                .computeBytesSizeNoTag(element);
          }
        }
        size += dataSize;
        size += 1 * dataCount;
      }
      return size;
    }
    
    @Override
    public Domain mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.strDomain = input.readBytes();
            break;
          }
          case 18: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 18);
            int i = this.rptStrIp == null ? 0 : this.rptStrIp.length;
            byte[][] newArray = new byte[i + arrayLength][];
            if (i != 0) {
              java.lang.System.arraycopy(this.rptStrIp, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = input.readBytes();
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = input.readBytes();
            this.rptStrIp = newArray;
            break;
          }
        }
      }
    }
    
    public static Domain parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Domain(), data);
    }
    
    public static Domain parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Domain().mergeFrom(input);
    }
  }
  
  public static final class Req_ParseDomains extends
      com.google.protobuf.nano.MessageNano {
    
    private static volatile Req_ParseDomains[] _emptyArray;
    public static Req_ParseDomains[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Req_ParseDomains[0];
          }
        }
      }
      return _emptyArray;
    }
    
    // repeated .com.txz.ui.domain.Domain rpt_domains = 1;
    public com.txz.ui.domain.UiDomain.Domain[] rptDomains;
    
    public Req_ParseDomains() {
      clear();
    }
    
    public Req_ParseDomains clear() {
      rptDomains = com.txz.ui.domain.UiDomain.Domain.emptyArray();
      cachedSize = -1;
      return this;
    }
    
    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.rptDomains != null && this.rptDomains.length > 0) {
        for (int i = 0; i < this.rptDomains.length; i++) {
          com.txz.ui.domain.UiDomain.Domain element = this.rptDomains[i];
          if (element != null) {
            output.writeMessage(1, element);
          }
        }
      }
      super.writeTo(output);
    }
    
    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.rptDomains != null && this.rptDomains.length > 0) {
        for (int i = 0; i < this.rptDomains.length; i++) {
          com.txz.ui.domain.UiDomain.Domain element = this.rptDomains[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(1, element);
          }
        }
      }
      return size;
    }
    
    @Override
    public Req_ParseDomains mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 10);
            int i = this.rptDomains == null ? 0 : this.rptDomains.length;
            com.txz.ui.domain.UiDomain.Domain[] newArray =
                new com.txz.ui.domain.UiDomain.Domain[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.rptDomains, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new com.txz.ui.domain.UiDomain.Domain();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new com.txz.ui.domain.UiDomain.Domain();
            input.readMessage(newArray[i]);
            this.rptDomains = newArray;
            break;
          }
        }
      }
    }
    
    public static Req_ParseDomains parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Req_ParseDomains(), data);
    }
    
    public static Req_ParseDomains parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Req_ParseDomains().mergeFrom(input);
    }
  }
  
  public static final class Req_ReportDomains extends
      com.google.protobuf.nano.MessageNano {
    
    private static volatile Req_ReportDomains[] _emptyArray;
    public static Req_ReportDomains[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Req_ReportDomains[0];
          }
        }
      }
      return _emptyArray;
    }
    
    // repeated .com.txz.ui.domain.Domain rpt_domains = 1;
    public com.txz.ui.domain.UiDomain.Domain[] rptDomains;
    
    public Req_ReportDomains() {
      clear();
    }
    
    public Req_ReportDomains clear() {
      rptDomains = com.txz.ui.domain.UiDomain.Domain.emptyArray();
      cachedSize = -1;
      return this;
    }
    
    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.rptDomains != null && this.rptDomains.length > 0) {
        for (int i = 0; i < this.rptDomains.length; i++) {
          com.txz.ui.domain.UiDomain.Domain element = this.rptDomains[i];
          if (element != null) {
            output.writeMessage(1, element);
          }
        }
      }
      super.writeTo(output);
    }
    
    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.rptDomains != null && this.rptDomains.length > 0) {
        for (int i = 0; i < this.rptDomains.length; i++) {
          com.txz.ui.domain.UiDomain.Domain element = this.rptDomains[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(1, element);
          }
        }
      }
      return size;
    }
    
    @Override
    public Req_ReportDomains mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 10);
            int i = this.rptDomains == null ? 0 : this.rptDomains.length;
            com.txz.ui.domain.UiDomain.Domain[] newArray =
                new com.txz.ui.domain.UiDomain.Domain[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.rptDomains, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new com.txz.ui.domain.UiDomain.Domain();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new com.txz.ui.domain.UiDomain.Domain();
            input.readMessage(newArray[i]);
            this.rptDomains = newArray;
            break;
          }
        }
      }
    }
    
    public static Req_ReportDomains parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Req_ReportDomains(), data);
    }
    
    public static Req_ReportDomains parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Req_ReportDomains().mergeFrom(input);
    }
  }
}
