// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.txz.ui.tts;

@SuppressWarnings("hiding")
public interface UiTts {
  
  // enum SubEventId
  public static final int SUBEVENT_DEFAULT = 0;
  public static final int SUBEVENT_TTSTHEME_SET_REQ = 1;
  public static final int SUBEVENT_TTSTHEME_DOWN_REQ = 2;
  public static final int SUBEVENT_TTSTHEME_QUERY_REQ = 3;
  public static final int SUBEVENT_TTSTHEME_SET_RESP = 4;
  public static final int SUBEVENT_TTSTHEME_DOWN_RESP = 5;
  public static final int SUBEVENT_TTSTHEME_QUERY_RESP = 6;
  public static final int SUBEVENT_TTSTHEME_DOWN_PATCH_REQ = 7;
  public static final int SUBEVENT_TTSTHEME_DOWN_PATCH_RESP = 8;
  public static final int SUBEVENT_TTS_SPEAK_TEXT_REQ = 9;
  
  public static final class TTSTheme extends
      com.google.protobuf.nano.MessageNano {
    
    private static volatile TTSTheme[] _emptyArray;
    public static TTSTheme[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new TTSTheme[0];
          }
        }
      }
      return _emptyArray;
    }
    
    // optional uint32 uint32_theme_id = 1;
    public java.lang.Integer uint32ThemeId;
    
    // optional bytes str_theme_name = 2;
    public byte[] strThemeName;
    
    public TTSTheme() {
      clear();
    }
    
    public TTSTheme clear() {
      uint32ThemeId = null;
      strThemeName = null;
      cachedSize = -1;
      return this;
    }
    
    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.uint32ThemeId != null) {
        output.writeUInt32(1, this.uint32ThemeId);
      }
      if (this.strThemeName != null) {
        output.writeBytes(2, this.strThemeName);
      }
      super.writeTo(output);
    }
    
    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.uint32ThemeId != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(1, this.uint32ThemeId);
      }
      if (this.strThemeName != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBytesSize(2, this.strThemeName);
      }
      return size;
    }
    
    @Override
    public TTSTheme mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.uint32ThemeId = input.readUInt32();
            break;
          }
          case 18: {
            this.strThemeName = input.readBytes();
            break;
          }
        }
      }
    }
    
    public static TTSTheme parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new TTSTheme(), data);
    }
    
    public static TTSTheme parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new TTSTheme().mergeFrom(input);
    }
  }
  
  public static final class TTSThemeConfig extends
      com.google.protobuf.nano.MessageNano {
    
    private static volatile TTSThemeConfig[] _emptyArray;
    public static TTSThemeConfig[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new TTSThemeConfig[0];
          }
        }
      }
      return _emptyArray;
    }
    
    // optional .com.txz.ui.tts.TTSTheme msg_theme = 1;
    public com.txz.ui.tts.UiTts.TTSTheme msgTheme;
    
    // optional uint64 uint64_config_time = 2;
    public java.lang.Long uint64ConfigTime;
    
    public TTSThemeConfig() {
      clear();
    }
    
    public TTSThemeConfig clear() {
      msgTheme = null;
      uint64ConfigTime = null;
      cachedSize = -1;
      return this;
    }
    
    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.msgTheme != null) {
        output.writeMessage(1, this.msgTheme);
      }
      if (this.uint64ConfigTime != null) {
        output.writeUInt64(2, this.uint64ConfigTime);
      }
      super.writeTo(output);
    }
    
    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.msgTheme != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.msgTheme);
      }
      if (this.uint64ConfigTime != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt64Size(2, this.uint64ConfigTime);
      }
      return size;
    }
    
    @Override
    public TTSThemeConfig mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.msgTheme == null) {
              this.msgTheme = new com.txz.ui.tts.UiTts.TTSTheme();
            }
            input.readMessage(this.msgTheme);
            break;
          }
          case 16: {
            this.uint64ConfigTime = input.readUInt64();
            break;
          }
        }
      }
    }
    
    public static TTSThemeConfig parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new TTSThemeConfig(), data);
    }
    
    public static TTSThemeConfig parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new TTSThemeConfig().mergeFrom(input);
    }
  }
  
  public static final class TTSConfig extends
      com.google.protobuf.nano.MessageNano {
    
    private static volatile TTSConfig[] _emptyArray;
    public static TTSConfig[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new TTSConfig[0];
          }
        }
      }
      return _emptyArray;
    }
    
    // optional .com.txz.ui.tts.TTSThemeConfig msg_current_theme_config = 1;
    public com.txz.ui.tts.UiTts.TTSThemeConfig msgCurrentThemeConfig;
    
    public TTSConfig() {
      clear();
    }
    
    public TTSConfig clear() {
      msgCurrentThemeConfig = null;
      cachedSize = -1;
      return this;
    }
    
    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.msgCurrentThemeConfig != null) {
        output.writeMessage(1, this.msgCurrentThemeConfig);
      }
      super.writeTo(output);
    }
    
    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.msgCurrentThemeConfig != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.msgCurrentThemeConfig);
      }
      return size;
    }
    
    @Override
    public TTSConfig mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.msgCurrentThemeConfig == null) {
              this.msgCurrentThemeConfig = new com.txz.ui.tts.UiTts.TTSThemeConfig();
            }
            input.readMessage(this.msgCurrentThemeConfig);
            break;
          }
        }
      }
    }
    
    public static TTSConfig parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new TTSConfig(), data);
    }
    
    public static TTSConfig parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new TTSConfig().mergeFrom(input);
    }
  }
}
