// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.txz.ui.wechat;

@SuppressWarnings("hiding")
public interface UiWechat {
  
  // enum SubEventId
  public static final int SUBEVENT_DEFAULT = 0;
  public static final int SUBEVENT_GET_WECHAT_LOGIN_STATE = 1;
  public static final int SUBEVENT_NOTIFY_WECHAT_LOGIN_STATE = 2;
  public static final int SUBEVENT_START_VOICE = 101;
  public static final int SUBEVENT_UPLOAD_VOICE = 102;
  public static final int SUBEVENT_CANCEL_VOICE = 103;
  public static final int SUBEVENT_END_VOICE = 104;
  public static final int SUBEVENT_UPLOAD_VOICE_RESULT = 105;
  public static final int SUBEVENT_ERR_NO_CONTACT = 201;
  
  public static final class WechatVoiceTask extends
      com.google.protobuf.nano.MessageNano {
    
    private static volatile WechatVoiceTask[] _emptyArray;
    public static WechatVoiceTask[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new WechatVoiceTask[0];
          }
        }
      }
      return _emptyArray;
    }
    
    // optional uint64 uint64_timestamp = 1;
    public java.lang.Long uint64Timestamp;
    
    // optional bytes bytes_pcm = 2;
    public byte[] bytesPcm;
    
    // optional uint32 uint32_tail_len = 3;
    public java.lang.Integer uint32TailLen;
    
    // optional bytes str_tail_text = 4;
    public byte[] strTailText;
    
    public WechatVoiceTask() {
      clear();
    }
    
    public WechatVoiceTask clear() {
      uint64Timestamp = null;
      bytesPcm = null;
      uint32TailLen = null;
      strTailText = null;
      cachedSize = -1;
      return this;
    }
    
    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.uint64Timestamp != null) {
        output.writeUInt64(1, this.uint64Timestamp);
      }
      if (this.bytesPcm != null) {
        output.writeBytes(2, this.bytesPcm);
      }
      if (this.uint32TailLen != null) {
        output.writeUInt32(3, this.uint32TailLen);
      }
      if (this.strTailText != null) {
        output.writeBytes(4, this.strTailText);
      }
      super.writeTo(output);
    }
    
    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.uint64Timestamp != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt64Size(1, this.uint64Timestamp);
      }
      if (this.bytesPcm != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBytesSize(2, this.bytesPcm);
      }
      if (this.uint32TailLen != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(3, this.uint32TailLen);
      }
      if (this.strTailText != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBytesSize(4, this.strTailText);
      }
      return size;
    }
    
    @Override
    public WechatVoiceTask mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.uint64Timestamp = input.readUInt64();
            break;
          }
          case 18: {
            this.bytesPcm = input.readBytes();
            break;
          }
          case 24: {
            this.uint32TailLen = input.readUInt32();
            break;
          }
          case 34: {
            this.strTailText = input.readBytes();
            break;
          }
        }
      }
    }
    
    public static WechatVoiceTask parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new WechatVoiceTask(), data);
    }
    
    public static WechatVoiceTask parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new WechatVoiceTask().mergeFrom(input);
    }
  }
  
  public static final class WechatVoiceMessage extends
      com.google.protobuf.nano.MessageNano {
    
    private static volatile WechatVoiceMessage[] _emptyArray;
    public static WechatVoiceMessage[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new WechatVoiceMessage[0];
          }
        }
      }
      return _emptyArray;
    }
    
    // optional uint64 uint64_timestamp = 1;
    public java.lang.Long uint64Timestamp;
    
    // optional bool bool_success = 2;
    public java.lang.Boolean boolSuccess;
    
    // optional string str_err_desc = 3;
    public java.lang.String strErrDesc;
    
    // optional uint32 uint32_voice_len = 4;
    public java.lang.Integer uint32VoiceLen;
    
    // optional string str_voice_pcm = 5;
    public java.lang.String strVoicePcm;
    
    // optional string str_voice_url = 6;
    public java.lang.String strVoiceUrl;
    
    // optional string str_voice_txt = 7;
    public java.lang.String strVoiceTxt;
    
    public WechatVoiceMessage() {
      clear();
    }
    
    public WechatVoiceMessage clear() {
      uint64Timestamp = null;
      boolSuccess = null;
      strErrDesc = null;
      uint32VoiceLen = null;
      strVoicePcm = null;
      strVoiceUrl = null;
      strVoiceTxt = null;
      cachedSize = -1;
      return this;
    }
    
    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.uint64Timestamp != null) {
        output.writeUInt64(1, this.uint64Timestamp);
      }
      if (this.boolSuccess != null) {
        output.writeBool(2, this.boolSuccess);
      }
      if (this.strErrDesc != null) {
        output.writeString(3, this.strErrDesc);
      }
      if (this.uint32VoiceLen != null) {
        output.writeUInt32(4, this.uint32VoiceLen);
      }
      if (this.strVoicePcm != null) {
        output.writeString(5, this.strVoicePcm);
      }
      if (this.strVoiceUrl != null) {
        output.writeString(6, this.strVoiceUrl);
      }
      if (this.strVoiceTxt != null) {
        output.writeString(7, this.strVoiceTxt);
      }
      super.writeTo(output);
    }
    
    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.uint64Timestamp != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt64Size(1, this.uint64Timestamp);
      }
      if (this.boolSuccess != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(2, this.boolSuccess);
      }
      if (this.strErrDesc != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(3, this.strErrDesc);
      }
      if (this.uint32VoiceLen != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(4, this.uint32VoiceLen);
      }
      if (this.strVoicePcm != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(5, this.strVoicePcm);
      }
      if (this.strVoiceUrl != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(6, this.strVoiceUrl);
      }
      if (this.strVoiceTxt != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(7, this.strVoiceTxt);
      }
      return size;
    }
    
    @Override
    public WechatVoiceMessage mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.uint64Timestamp = input.readUInt64();
            break;
          }
          case 16: {
            this.boolSuccess = input.readBool();
            break;
          }
          case 26: {
            this.strErrDesc = input.readString();
            break;
          }
          case 32: {
            this.uint32VoiceLen = input.readUInt32();
            break;
          }
          case 42: {
            this.strVoicePcm = input.readString();
            break;
          }
          case 50: {
            this.strVoiceUrl = input.readString();
            break;
          }
          case 58: {
            this.strVoiceTxt = input.readString();
            break;
          }
        }
      }
    }
    
    public static WechatVoiceMessage parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new WechatVoiceMessage(), data);
    }
    
    public static WechatVoiceMessage parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new WechatVoiceMessage().mergeFrom(input);
    }
  }
}
