// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.txz.music_manager;

@SuppressWarnings("hiding")
public interface MusicManager {
  
  // enum SubCommand
  public static final int SUBCMD_MUSIC_DEFAULT = 0;
  public static final int SUBCMD_MUSIC_DOWNLOAD_LIST = 1;
  public static final int SUBCMD_MUSIC_GET_DESC_LIST = 2;
  public static final int SUBCMD_MUSIC_SEARCH = 3;
  public static final int SUBCMD_MUSIC_GET_CATEGORY_LIST = 4;
  public static final int SUBCMD_MUSIC_GET_SONG_LIST_BY_CATEGORY = 5;
  public static final int SUBCMD_MUSIC_FM_SEARCH = 6;
  
  // enum ErrorCode
  public static final int EC_DEFAULT = 0;
  public static final int EC_SAVE_ERR = 6001;
  public static final int EC_NEED_INSTALL_QQ_MUSIC = 6002;
  public static final int EC_NEED_INSTALL_KAOLA_FM = 6003;
  public static final int EC_NEED_INSTALL_FM_OR_MUSIC_APP = 6004;
  
  public static final class MusicSinger extends
      com.google.protobuf.nano.MessageNano {
    
    private static volatile MusicSinger[] _emptyArray;
    public static MusicSinger[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new MusicSinger[0];
          }
        }
      }
      return _emptyArray;
    }
    
    // optional uint32 uint32_id = 1;
    public java.lang.Integer uint32Id;
    
    // optional string str_name = 2;
    public java.lang.String strName;
    
    public MusicSinger() {
      clear();
    }
    
    public MusicSinger clear() {
      uint32Id = null;
      strName = null;
      cachedSize = -1;
      return this;
    }
    
    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.uint32Id != null) {
        output.writeUInt32(1, this.uint32Id);
      }
      if (this.strName != null) {
        output.writeString(2, this.strName);
      }
      super.writeTo(output);
    }
    
    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.uint32Id != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(1, this.uint32Id);
      }
      if (this.strName != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.strName);
      }
      return size;
    }
    
    @Override
    public MusicSinger mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.uint32Id = input.readUInt32();
            break;
          }
          case 18: {
            this.strName = input.readString();
            break;
          }
        }
      }
    }
    
    public static MusicSinger parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new MusicSinger(), data);
    }
    
    public static MusicSinger parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new MusicSinger().mergeFrom(input);
    }
  }
  
  public static final class MusicRecord extends
      com.google.protobuf.nano.MessageNano {
    
    private static volatile MusicRecord[] _emptyArray;
    public static MusicRecord[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new MusicRecord[0];
          }
        }
      }
      return _emptyArray;
    }
    
    // optional uint32 uint32_song_id = 1;
    public java.lang.Integer uint32SongId;
    
    // optional string str_song_name = 2;
    public java.lang.String strSongName;
    
    // optional uint32 uint32_album_id = 3;
    public java.lang.Integer uint32AlbumId;
    
    // optional string str_album_name = 4;
    public java.lang.String strAlbumName;
    
    // repeated .com.txz.music_manager.MusicSinger rpt_msg_singer = 5;
    public com.txz.music_manager.MusicManager.MusicSinger[] rptMsgSinger;
    
    // repeated string rpt_str_tags = 6;
    public java.lang.String[] rptStrTags;
    
    // optional bool b_local = 7;
    public java.lang.Boolean bLocal;
    
    // optional string str_mmid = 8;
    public java.lang.String strMmid;
    
    // optional string str_path = 9;
    public java.lang.String strPath;
    
    // optional bool b_favourite = 10;
    public java.lang.Boolean bFavourite;
    
    // optional uint32 uint32_download_type = 11;
    public java.lang.Integer uint32DownloadType;
    
    // optional string str_package_name = 12;
    public java.lang.String strPackageName;
    
    // optional string str_url = 13;
    public java.lang.String strUrl;
    
    public MusicRecord() {
      clear();
    }
    
    public MusicRecord clear() {
      uint32SongId = null;
      strSongName = null;
      uint32AlbumId = null;
      strAlbumName = null;
      rptMsgSinger = com.txz.music_manager.MusicManager.MusicSinger.emptyArray();
      rptStrTags = com.google.protobuf.nano.WireFormatNano.EMPTY_STRING_ARRAY;
      bLocal = null;
      strMmid = null;
      strPath = null;
      bFavourite = null;
      uint32DownloadType = null;
      strPackageName = null;
      strUrl = null;
      cachedSize = -1;
      return this;
    }
    
    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.uint32SongId != null) {
        output.writeUInt32(1, this.uint32SongId);
      }
      if (this.strSongName != null) {
        output.writeString(2, this.strSongName);
      }
      if (this.uint32AlbumId != null) {
        output.writeUInt32(3, this.uint32AlbumId);
      }
      if (this.strAlbumName != null) {
        output.writeString(4, this.strAlbumName);
      }
      if (this.rptMsgSinger != null && this.rptMsgSinger.length > 0) {
        for (int i = 0; i < this.rptMsgSinger.length; i++) {
          com.txz.music_manager.MusicManager.MusicSinger element = this.rptMsgSinger[i];
          if (element != null) {
            output.writeMessage(5, element);
          }
        }
      }
      if (this.rptStrTags != null && this.rptStrTags.length > 0) {
        for (int i = 0; i < this.rptStrTags.length; i++) {
          java.lang.String element = this.rptStrTags[i];
          if (element != null) {
            output.writeString(6, element);
          }
        }
      }
      if (this.bLocal != null) {
        output.writeBool(7, this.bLocal);
      }
      if (this.strMmid != null) {
        output.writeString(8, this.strMmid);
      }
      if (this.strPath != null) {
        output.writeString(9, this.strPath);
      }
      if (this.bFavourite != null) {
        output.writeBool(10, this.bFavourite);
      }
      if (this.uint32DownloadType != null) {
        output.writeUInt32(11, this.uint32DownloadType);
      }
      if (this.strPackageName != null) {
        output.writeString(12, this.strPackageName);
      }
      if (this.strUrl != null) {
        output.writeString(13, this.strUrl);
      }
      super.writeTo(output);
    }
    
    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.uint32SongId != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(1, this.uint32SongId);
      }
      if (this.strSongName != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.strSongName);
      }
      if (this.uint32AlbumId != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(3, this.uint32AlbumId);
      }
      if (this.strAlbumName != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(4, this.strAlbumName);
      }
      if (this.rptMsgSinger != null && this.rptMsgSinger.length > 0) {
        for (int i = 0; i < this.rptMsgSinger.length; i++) {
          com.txz.music_manager.MusicManager.MusicSinger element = this.rptMsgSinger[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(5, element);
          }
        }
      }
      if (this.rptStrTags != null && this.rptStrTags.length > 0) {
        int dataCount = 0;
        int dataSize = 0;
        for (int i = 0; i < this.rptStrTags.length; i++) {
          java.lang.String element = this.rptStrTags[i];
          if (element != null) {
            dataCount++;
            dataSize += com.google.protobuf.nano.CodedOutputByteBufferNano
                .computeStringSizeNoTag(element);
          }
        }
        size += dataSize;
        size += 1 * dataCount;
      }
      if (this.bLocal != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(7, this.bLocal);
      }
      if (this.strMmid != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(8, this.strMmid);
      }
      if (this.strPath != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(9, this.strPath);
      }
      if (this.bFavourite != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(10, this.bFavourite);
      }
      if (this.uint32DownloadType != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(11, this.uint32DownloadType);
      }
      if (this.strPackageName != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(12, this.strPackageName);
      }
      if (this.strUrl != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(13, this.strUrl);
      }
      return size;
    }
    
    @Override
    public MusicRecord mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.uint32SongId = input.readUInt32();
            break;
          }
          case 18: {
            this.strSongName = input.readString();
            break;
          }
          case 24: {
            this.uint32AlbumId = input.readUInt32();
            break;
          }
          case 34: {
            this.strAlbumName = input.readString();
            break;
          }
          case 42: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 42);
            int i = this.rptMsgSinger == null ? 0 : this.rptMsgSinger.length;
            com.txz.music_manager.MusicManager.MusicSinger[] newArray =
                new com.txz.music_manager.MusicManager.MusicSinger[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.rptMsgSinger, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new com.txz.music_manager.MusicManager.MusicSinger();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new com.txz.music_manager.MusicManager.MusicSinger();
            input.readMessage(newArray[i]);
            this.rptMsgSinger = newArray;
            break;
          }
          case 50: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 50);
            int i = this.rptStrTags == null ? 0 : this.rptStrTags.length;
            java.lang.String[] newArray = new java.lang.String[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.rptStrTags, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = input.readString();
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = input.readString();
            this.rptStrTags = newArray;
            break;
          }
          case 56: {
            this.bLocal = input.readBool();
            break;
          }
          case 66: {
            this.strMmid = input.readString();
            break;
          }
          case 74: {
            this.strPath = input.readString();
            break;
          }
          case 80: {
            this.bFavourite = input.readBool();
            break;
          }
          case 88: {
            this.uint32DownloadType = input.readUInt32();
            break;
          }
          case 98: {
            this.strPackageName = input.readString();
            break;
          }
          case 106: {
            this.strUrl = input.readString();
            break;
          }
        }
      }
    }
    
    public static MusicRecord parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new MusicRecord(), data);
    }
    
    public static MusicRecord parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new MusicRecord().mergeFrom(input);
    }
  }
  
  public static final class MusicCategory extends
      com.google.protobuf.nano.MessageNano {
    
    private static volatile MusicCategory[] _emptyArray;
    public static MusicCategory[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new MusicCategory[0];
          }
        }
      }
      return _emptyArray;
    }
    
    // optional uint32 uint32_id = 1;
    public java.lang.Integer uint32Id;
    
    // optional string str_name = 2;
    public java.lang.String strName;
    
    // optional uint32 uint32_song_cnt = 3;
    public java.lang.Integer uint32SongCnt;
    
    // optional uint32 uint32_update_time = 4;
    public java.lang.Integer uint32UpdateTime;
    
    public MusicCategory() {
      clear();
    }
    
    public MusicCategory clear() {
      uint32Id = null;
      strName = null;
      uint32SongCnt = null;
      uint32UpdateTime = null;
      cachedSize = -1;
      return this;
    }
    
    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.uint32Id != null) {
        output.writeUInt32(1, this.uint32Id);
      }
      if (this.strName != null) {
        output.writeString(2, this.strName);
      }
      if (this.uint32SongCnt != null) {
        output.writeUInt32(3, this.uint32SongCnt);
      }
      if (this.uint32UpdateTime != null) {
        output.writeUInt32(4, this.uint32UpdateTime);
      }
      super.writeTo(output);
    }
    
    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.uint32Id != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(1, this.uint32Id);
      }
      if (this.strName != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.strName);
      }
      if (this.uint32SongCnt != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(3, this.uint32SongCnt);
      }
      if (this.uint32UpdateTime != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(4, this.uint32UpdateTime);
      }
      return size;
    }
    
    @Override
    public MusicCategory mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.uint32Id = input.readUInt32();
            break;
          }
          case 18: {
            this.strName = input.readString();
            break;
          }
          case 24: {
            this.uint32SongCnt = input.readUInt32();
            break;
          }
          case 32: {
            this.uint32UpdateTime = input.readUInt32();
            break;
          }
        }
      }
    }
    
    public static MusicCategory parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new MusicCategory(), data);
    }
    
    public static MusicCategory parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new MusicCategory().mergeFrom(input);
    }
  }
  
  public static final class Req_GetDescription extends
      com.google.protobuf.nano.MessageNano {
    
    private static volatile Req_GetDescription[] _emptyArray;
    public static Req_GetDescription[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Req_GetDescription[0];
          }
        }
      }
      return _emptyArray;
    }
    
    // repeated .com.txz.ui.music.MediaModel rpt_music_list = 1;
    public com.txz.ui.music.UiMusic.MediaModel[] rptMusicList;
    
    public Req_GetDescription() {
      clear();
    }
    
    public Req_GetDescription clear() {
      rptMusicList = com.txz.ui.music.UiMusic.MediaModel.emptyArray();
      cachedSize = -1;
      return this;
    }
    
    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.rptMusicList != null && this.rptMusicList.length > 0) {
        for (int i = 0; i < this.rptMusicList.length; i++) {
          com.txz.ui.music.UiMusic.MediaModel element = this.rptMusicList[i];
          if (element != null) {
            output.writeMessage(1, element);
          }
        }
      }
      super.writeTo(output);
    }
    
    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.rptMusicList != null && this.rptMusicList.length > 0) {
        for (int i = 0; i < this.rptMusicList.length; i++) {
          com.txz.ui.music.UiMusic.MediaModel element = this.rptMusicList[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(1, element);
          }
        }
      }
      return size;
    }
    
    @Override
    public Req_GetDescription mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 10);
            int i = this.rptMusicList == null ? 0 : this.rptMusicList.length;
            com.txz.ui.music.UiMusic.MediaModel[] newArray =
                new com.txz.ui.music.UiMusic.MediaModel[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.rptMusicList, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new com.txz.ui.music.UiMusic.MediaModel();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new com.txz.ui.music.UiMusic.MediaModel();
            input.readMessage(newArray[i]);
            this.rptMusicList = newArray;
            break;
          }
        }
      }
    }
    
    public static Req_GetDescription parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Req_GetDescription(), data);
    }
    
    public static Req_GetDescription parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Req_GetDescription().mergeFrom(input);
    }
  }
  
  public static final class Resp_GetDescription extends
      com.google.protobuf.nano.MessageNano {
    
    private static volatile Resp_GetDescription[] _emptyArray;
    public static Resp_GetDescription[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Resp_GetDescription[0];
          }
        }
      }
      return _emptyArray;
    }
    
    // optional bool b_ok = 1;
    public java.lang.Boolean bOk;
    
    // repeated .com.txz.ui.music.MediaModel rpt_music_list = 2;
    public com.txz.ui.music.UiMusic.MediaModel[] rptMusicList;
    
    public Resp_GetDescription() {
      clear();
    }
    
    public Resp_GetDescription clear() {
      bOk = null;
      rptMusicList = com.txz.ui.music.UiMusic.MediaModel.emptyArray();
      cachedSize = -1;
      return this;
    }
    
    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.bOk != null) {
        output.writeBool(1, this.bOk);
      }
      if (this.rptMusicList != null && this.rptMusicList.length > 0) {
        for (int i = 0; i < this.rptMusicList.length; i++) {
          com.txz.ui.music.UiMusic.MediaModel element = this.rptMusicList[i];
          if (element != null) {
            output.writeMessage(2, element);
          }
        }
      }
      super.writeTo(output);
    }
    
    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.bOk != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(1, this.bOk);
      }
      if (this.rptMusicList != null && this.rptMusicList.length > 0) {
        for (int i = 0; i < this.rptMusicList.length; i++) {
          com.txz.ui.music.UiMusic.MediaModel element = this.rptMusicList[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(2, element);
          }
        }
      }
      return size;
    }
    
    @Override
    public Resp_GetDescription mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.bOk = input.readBool();
            break;
          }
          case 18: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 18);
            int i = this.rptMusicList == null ? 0 : this.rptMusicList.length;
            com.txz.ui.music.UiMusic.MediaModel[] newArray =
                new com.txz.ui.music.UiMusic.MediaModel[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.rptMusicList, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new com.txz.ui.music.UiMusic.MediaModel();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new com.txz.ui.music.UiMusic.MediaModel();
            input.readMessage(newArray[i]);
            this.rptMusicList = newArray;
            break;
          }
        }
      }
    }
    
    public static Resp_GetDescription parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Resp_GetDescription(), data);
    }
    
    public static Resp_GetDescription parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Resp_GetDescription().mergeFrom(input);
    }
  }
  
  public static final class Req_DownloadList extends
      com.google.protobuf.nano.MessageNano {
    
    private static volatile Req_DownloadList[] _emptyArray;
    public static Req_DownloadList[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Req_DownloadList[0];
          }
        }
      }
      return _emptyArray;
    }
    
    // repeated .com.txz.music_manager.MusicRecord rpt_music_list = 1;
    public com.txz.music_manager.MusicManager.MusicRecord[] rptMusicList;
    
    public Req_DownloadList() {
      clear();
    }
    
    public Req_DownloadList clear() {
      rptMusicList = com.txz.music_manager.MusicManager.MusicRecord.emptyArray();
      cachedSize = -1;
      return this;
    }
    
    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.rptMusicList != null && this.rptMusicList.length > 0) {
        for (int i = 0; i < this.rptMusicList.length; i++) {
          com.txz.music_manager.MusicManager.MusicRecord element = this.rptMusicList[i];
          if (element != null) {
            output.writeMessage(1, element);
          }
        }
      }
      super.writeTo(output);
    }
    
    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.rptMusicList != null && this.rptMusicList.length > 0) {
        for (int i = 0; i < this.rptMusicList.length; i++) {
          com.txz.music_manager.MusicManager.MusicRecord element = this.rptMusicList[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(1, element);
          }
        }
      }
      return size;
    }
    
    @Override
    public Req_DownloadList mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 10);
            int i = this.rptMusicList == null ? 0 : this.rptMusicList.length;
            com.txz.music_manager.MusicManager.MusicRecord[] newArray =
                new com.txz.music_manager.MusicManager.MusicRecord[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.rptMusicList, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new com.txz.music_manager.MusicManager.MusicRecord();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new com.txz.music_manager.MusicManager.MusicRecord();
            input.readMessage(newArray[i]);
            this.rptMusicList = newArray;
            break;
          }
        }
      }
    }
    
    public static Req_DownloadList parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Req_DownloadList(), data);
    }
    
    public static Req_DownloadList parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Req_DownloadList().mergeFrom(input);
    }
  }
  
  public static final class Resp_DownloadList extends
      com.google.protobuf.nano.MessageNano {
    
    private static volatile Resp_DownloadList[] _emptyArray;
    public static Resp_DownloadList[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Resp_DownloadList[0];
          }
        }
      }
      return _emptyArray;
    }
    
    // optional bool b_ok = 1;
    public java.lang.Boolean bOk;
    
    // repeated .com.txz.music_manager.MusicRecord rpt_music_list = 2;
    public com.txz.music_manager.MusicManager.MusicRecord[] rptMusicList;
    
    // repeated .com.txz.music_manager.MusicRecord rpt_del_list = 3;
    public com.txz.music_manager.MusicManager.MusicRecord[] rptDelList;
    
    public Resp_DownloadList() {
      clear();
    }
    
    public Resp_DownloadList clear() {
      bOk = null;
      rptMusicList = com.txz.music_manager.MusicManager.MusicRecord.emptyArray();
      rptDelList = com.txz.music_manager.MusicManager.MusicRecord.emptyArray();
      cachedSize = -1;
      return this;
    }
    
    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.bOk != null) {
        output.writeBool(1, this.bOk);
      }
      if (this.rptMusicList != null && this.rptMusicList.length > 0) {
        for (int i = 0; i < this.rptMusicList.length; i++) {
          com.txz.music_manager.MusicManager.MusicRecord element = this.rptMusicList[i];
          if (element != null) {
            output.writeMessage(2, element);
          }
        }
      }
      if (this.rptDelList != null && this.rptDelList.length > 0) {
        for (int i = 0; i < this.rptDelList.length; i++) {
          com.txz.music_manager.MusicManager.MusicRecord element = this.rptDelList[i];
          if (element != null) {
            output.writeMessage(3, element);
          }
        }
      }
      super.writeTo(output);
    }
    
    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.bOk != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(1, this.bOk);
      }
      if (this.rptMusicList != null && this.rptMusicList.length > 0) {
        for (int i = 0; i < this.rptMusicList.length; i++) {
          com.txz.music_manager.MusicManager.MusicRecord element = this.rptMusicList[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(2, element);
          }
        }
      }
      if (this.rptDelList != null && this.rptDelList.length > 0) {
        for (int i = 0; i < this.rptDelList.length; i++) {
          com.txz.music_manager.MusicManager.MusicRecord element = this.rptDelList[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(3, element);
          }
        }
      }
      return size;
    }
    
    @Override
    public Resp_DownloadList mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.bOk = input.readBool();
            break;
          }
          case 18: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 18);
            int i = this.rptMusicList == null ? 0 : this.rptMusicList.length;
            com.txz.music_manager.MusicManager.MusicRecord[] newArray =
                new com.txz.music_manager.MusicManager.MusicRecord[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.rptMusicList, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new com.txz.music_manager.MusicManager.MusicRecord();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new com.txz.music_manager.MusicManager.MusicRecord();
            input.readMessage(newArray[i]);
            this.rptMusicList = newArray;
            break;
          }
          case 26: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 26);
            int i = this.rptDelList == null ? 0 : this.rptDelList.length;
            com.txz.music_manager.MusicManager.MusicRecord[] newArray =
                new com.txz.music_manager.MusicManager.MusicRecord[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.rptDelList, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new com.txz.music_manager.MusicManager.MusicRecord();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new com.txz.music_manager.MusicManager.MusicRecord();
            input.readMessage(newArray[i]);
            this.rptDelList = newArray;
            break;
          }
        }
      }
    }
    
    public static Resp_DownloadList parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Resp_DownloadList(), data);
    }
    
    public static Resp_DownloadList parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Resp_DownloadList().mergeFrom(input);
    }
  }
  
  public static final class Req_Search extends
      com.google.protobuf.nano.MessageNano {
    
    private static volatile Req_Search[] _emptyArray;
    public static Req_Search[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Req_Search[0];
          }
        }
      }
      return _emptyArray;
    }
    
    // optional .com.txz.ui.music.MediaModel msg_search_filter = 1;
    public com.txz.ui.music.UiMusic.MediaModel msgSearchFilter;
    
    public Req_Search() {
      clear();
    }
    
    public Req_Search clear() {
      msgSearchFilter = null;
      cachedSize = -1;
      return this;
    }
    
    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.msgSearchFilter != null) {
        output.writeMessage(1, this.msgSearchFilter);
      }
      super.writeTo(output);
    }
    
    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.msgSearchFilter != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.msgSearchFilter);
      }
      return size;
    }
    
    @Override
    public Req_Search mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.msgSearchFilter == null) {
              this.msgSearchFilter = new com.txz.ui.music.UiMusic.MediaModel();
            }
            input.readMessage(this.msgSearchFilter);
            break;
          }
        }
      }
    }
    
    public static Req_Search parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Req_Search(), data);
    }
    
    public static Req_Search parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Req_Search().mergeFrom(input);
    }
  }
  
  public static final class Resp_Search extends
      com.google.protobuf.nano.MessageNano {
    
    private static volatile Resp_Search[] _emptyArray;
    public static Resp_Search[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Resp_Search[0];
          }
        }
      }
      return _emptyArray;
    }
    
    // optional bool b_ok = 1;
    public java.lang.Boolean bOk;
    
    // repeated .com.txz.music_manager.MusicRecord rpt_music_list = 2;
    public com.txz.music_manager.MusicManager.MusicRecord[] rptMusicList;
    
    // optional .com.txz.ui.music.MediaModel msg_search_filter = 3;
    public com.txz.ui.music.UiMusic.MediaModel msgSearchFilter;
    
    public Resp_Search() {
      clear();
    }
    
    public Resp_Search clear() {
      bOk = null;
      rptMusicList = com.txz.music_manager.MusicManager.MusicRecord.emptyArray();
      msgSearchFilter = null;
      cachedSize = -1;
      return this;
    }
    
    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.bOk != null) {
        output.writeBool(1, this.bOk);
      }
      if (this.rptMusicList != null && this.rptMusicList.length > 0) {
        for (int i = 0; i < this.rptMusicList.length; i++) {
          com.txz.music_manager.MusicManager.MusicRecord element = this.rptMusicList[i];
          if (element != null) {
            output.writeMessage(2, element);
          }
        }
      }
      if (this.msgSearchFilter != null) {
        output.writeMessage(3, this.msgSearchFilter);
      }
      super.writeTo(output);
    }
    
    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.bOk != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(1, this.bOk);
      }
      if (this.rptMusicList != null && this.rptMusicList.length > 0) {
        for (int i = 0; i < this.rptMusicList.length; i++) {
          com.txz.music_manager.MusicManager.MusicRecord element = this.rptMusicList[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(2, element);
          }
        }
      }
      if (this.msgSearchFilter != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(3, this.msgSearchFilter);
      }
      return size;
    }
    
    @Override
    public Resp_Search mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.bOk = input.readBool();
            break;
          }
          case 18: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 18);
            int i = this.rptMusicList == null ? 0 : this.rptMusicList.length;
            com.txz.music_manager.MusicManager.MusicRecord[] newArray =
                new com.txz.music_manager.MusicManager.MusicRecord[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.rptMusicList, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new com.txz.music_manager.MusicManager.MusicRecord();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new com.txz.music_manager.MusicManager.MusicRecord();
            input.readMessage(newArray[i]);
            this.rptMusicList = newArray;
            break;
          }
          case 26: {
            if (this.msgSearchFilter == null) {
              this.msgSearchFilter = new com.txz.ui.music.UiMusic.MediaModel();
            }
            input.readMessage(this.msgSearchFilter);
            break;
          }
        }
      }
    }
    
    public static Resp_Search parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Resp_Search(), data);
    }
    
    public static Resp_Search parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Resp_Search().mergeFrom(input);
    }
  }
  
  public static final class Req_FMSearch extends
      com.google.protobuf.nano.MessageNano {
    
    private static volatile Req_FMSearch[] _emptyArray;
    public static Req_FMSearch[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Req_FMSearch[0];
          }
        }
      }
      return _emptyArray;
    }
    
    // optional .com.txz.ui.music.MediaModel msg_search_filter = 1;
    public com.txz.ui.music.UiMusic.MediaModel msgSearchFilter;
    
    // repeated string rpt_str_app_list = 2;
    public java.lang.String[] rptStrAppList;
    
    public Req_FMSearch() {
      clear();
    }
    
    public Req_FMSearch clear() {
      msgSearchFilter = null;
      rptStrAppList = com.google.protobuf.nano.WireFormatNano.EMPTY_STRING_ARRAY;
      cachedSize = -1;
      return this;
    }
    
    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.msgSearchFilter != null) {
        output.writeMessage(1, this.msgSearchFilter);
      }
      if (this.rptStrAppList != null && this.rptStrAppList.length > 0) {
        for (int i = 0; i < this.rptStrAppList.length; i++) {
          java.lang.String element = this.rptStrAppList[i];
          if (element != null) {
            output.writeString(2, element);
          }
        }
      }
      super.writeTo(output);
    }
    
    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.msgSearchFilter != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.msgSearchFilter);
      }
      if (this.rptStrAppList != null && this.rptStrAppList.length > 0) {
        int dataCount = 0;
        int dataSize = 0;
        for (int i = 0; i < this.rptStrAppList.length; i++) {
          java.lang.String element = this.rptStrAppList[i];
          if (element != null) {
            dataCount++;
            dataSize += com.google.protobuf.nano.CodedOutputByteBufferNano
                .computeStringSizeNoTag(element);
          }
        }
        size += dataSize;
        size += 1 * dataCount;
      }
      return size;
    }
    
    @Override
    public Req_FMSearch mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.msgSearchFilter == null) {
              this.msgSearchFilter = new com.txz.ui.music.UiMusic.MediaModel();
            }
            input.readMessage(this.msgSearchFilter);
            break;
          }
          case 18: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 18);
            int i = this.rptStrAppList == null ? 0 : this.rptStrAppList.length;
            java.lang.String[] newArray = new java.lang.String[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.rptStrAppList, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = input.readString();
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = input.readString();
            this.rptStrAppList = newArray;
            break;
          }
        }
      }
    }
    
    public static Req_FMSearch parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Req_FMSearch(), data);
    }
    
    public static Req_FMSearch parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Req_FMSearch().mergeFrom(input);
    }
  }
  
  public static final class Resp_FMSearch extends
      com.google.protobuf.nano.MessageNano {
    
    private static volatile Resp_FMSearch[] _emptyArray;
    public static Resp_FMSearch[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Resp_FMSearch[0];
          }
        }
      }
      return _emptyArray;
    }
    
    // optional bool b_ok = 1;
    public java.lang.Boolean bOk;
    
    // repeated .com.txz.music_manager.MusicRecord rpt_music_list = 2;
    public com.txz.music_manager.MusicManager.MusicRecord[] rptMusicList;
    
    // optional .com.txz.ui.music.MediaModel msg_search_filter = 3;
    public com.txz.ui.music.UiMusic.MediaModel msgSearchFilter;
    
    public Resp_FMSearch() {
      clear();
    }
    
    public Resp_FMSearch clear() {
      bOk = null;
      rptMusicList = com.txz.music_manager.MusicManager.MusicRecord.emptyArray();
      msgSearchFilter = null;
      cachedSize = -1;
      return this;
    }
    
    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.bOk != null) {
        output.writeBool(1, this.bOk);
      }
      if (this.rptMusicList != null && this.rptMusicList.length > 0) {
        for (int i = 0; i < this.rptMusicList.length; i++) {
          com.txz.music_manager.MusicManager.MusicRecord element = this.rptMusicList[i];
          if (element != null) {
            output.writeMessage(2, element);
          }
        }
      }
      if (this.msgSearchFilter != null) {
        output.writeMessage(3, this.msgSearchFilter);
      }
      super.writeTo(output);
    }
    
    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.bOk != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(1, this.bOk);
      }
      if (this.rptMusicList != null && this.rptMusicList.length > 0) {
        for (int i = 0; i < this.rptMusicList.length; i++) {
          com.txz.music_manager.MusicManager.MusicRecord element = this.rptMusicList[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(2, element);
          }
        }
      }
      if (this.msgSearchFilter != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(3, this.msgSearchFilter);
      }
      return size;
    }
    
    @Override
    public Resp_FMSearch mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.bOk = input.readBool();
            break;
          }
          case 18: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 18);
            int i = this.rptMusicList == null ? 0 : this.rptMusicList.length;
            com.txz.music_manager.MusicManager.MusicRecord[] newArray =
                new com.txz.music_manager.MusicManager.MusicRecord[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.rptMusicList, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new com.txz.music_manager.MusicManager.MusicRecord();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new com.txz.music_manager.MusicManager.MusicRecord();
            input.readMessage(newArray[i]);
            this.rptMusicList = newArray;
            break;
          }
          case 26: {
            if (this.msgSearchFilter == null) {
              this.msgSearchFilter = new com.txz.ui.music.UiMusic.MediaModel();
            }
            input.readMessage(this.msgSearchFilter);
            break;
          }
        }
      }
    }
    
    public static Resp_FMSearch parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Resp_FMSearch(), data);
    }
    
    public static Resp_FMSearch parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Resp_FMSearch().mergeFrom(input);
    }
  }
  
  public static final class Req_GetCategoryList extends
      com.google.protobuf.nano.MessageNano {
    
    private static volatile Req_GetCategoryList[] _emptyArray;
    public static Req_GetCategoryList[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Req_GetCategoryList[0];
          }
        }
      }
      return _emptyArray;
    }
    
    public Req_GetCategoryList() {
      clear();
    }
    
    public Req_GetCategoryList clear() {
      cachedSize = -1;
      return this;
    }
    
    @Override
    public Req_GetCategoryList mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
        }
      }
    }
    
    public static Req_GetCategoryList parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Req_GetCategoryList(), data);
    }
    
    public static Req_GetCategoryList parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Req_GetCategoryList().mergeFrom(input);
    }
  }
  
  public static final class Resp_GetCategoryList extends
      com.google.protobuf.nano.MessageNano {
    
    private static volatile Resp_GetCategoryList[] _emptyArray;
    public static Resp_GetCategoryList[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Resp_GetCategoryList[0];
          }
        }
      }
      return _emptyArray;
    }
    
    // repeated .com.txz.music_manager.MusicCategory rpt_category_list = 1;
    public com.txz.music_manager.MusicManager.MusicCategory[] rptCategoryList;
    
    public Resp_GetCategoryList() {
      clear();
    }
    
    public Resp_GetCategoryList clear() {
      rptCategoryList = com.txz.music_manager.MusicManager.MusicCategory.emptyArray();
      cachedSize = -1;
      return this;
    }
    
    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.rptCategoryList != null && this.rptCategoryList.length > 0) {
        for (int i = 0; i < this.rptCategoryList.length; i++) {
          com.txz.music_manager.MusicManager.MusicCategory element = this.rptCategoryList[i];
          if (element != null) {
            output.writeMessage(1, element);
          }
        }
      }
      super.writeTo(output);
    }
    
    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.rptCategoryList != null && this.rptCategoryList.length > 0) {
        for (int i = 0; i < this.rptCategoryList.length; i++) {
          com.txz.music_manager.MusicManager.MusicCategory element = this.rptCategoryList[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(1, element);
          }
        }
      }
      return size;
    }
    
    @Override
    public Resp_GetCategoryList mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 10);
            int i = this.rptCategoryList == null ? 0 : this.rptCategoryList.length;
            com.txz.music_manager.MusicManager.MusicCategory[] newArray =
                new com.txz.music_manager.MusicManager.MusicCategory[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.rptCategoryList, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new com.txz.music_manager.MusicManager.MusicCategory();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new com.txz.music_manager.MusicManager.MusicCategory();
            input.readMessage(newArray[i]);
            this.rptCategoryList = newArray;
            break;
          }
        }
      }
    }
    
    public static Resp_GetCategoryList parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Resp_GetCategoryList(), data);
    }
    
    public static Resp_GetCategoryList parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Resp_GetCategoryList().mergeFrom(input);
    }
  }
  
  public static final class Req_GetSongListByCategory extends
      com.google.protobuf.nano.MessageNano {
    
    private static volatile Req_GetSongListByCategory[] _emptyArray;
    public static Req_GetSongListByCategory[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Req_GetSongListByCategory[0];
          }
        }
      }
      return _emptyArray;
    }
    
    // optional uint32 uint32_id = 1;
    public java.lang.Integer uint32Id;
    
    // optional uint32 uint32_page_no = 2;
    public java.lang.Integer uint32PageNo;
    
    // optional uint32 uint32_count_of_page = 3;
    public java.lang.Integer uint32CountOfPage;
    
    public Req_GetSongListByCategory() {
      clear();
    }
    
    public Req_GetSongListByCategory clear() {
      uint32Id = null;
      uint32PageNo = null;
      uint32CountOfPage = null;
      cachedSize = -1;
      return this;
    }
    
    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.uint32Id != null) {
        output.writeUInt32(1, this.uint32Id);
      }
      if (this.uint32PageNo != null) {
        output.writeUInt32(2, this.uint32PageNo);
      }
      if (this.uint32CountOfPage != null) {
        output.writeUInt32(3, this.uint32CountOfPage);
      }
      super.writeTo(output);
    }
    
    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.uint32Id != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(1, this.uint32Id);
      }
      if (this.uint32PageNo != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(2, this.uint32PageNo);
      }
      if (this.uint32CountOfPage != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(3, this.uint32CountOfPage);
      }
      return size;
    }
    
    @Override
    public Req_GetSongListByCategory mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.uint32Id = input.readUInt32();
            break;
          }
          case 16: {
            this.uint32PageNo = input.readUInt32();
            break;
          }
          case 24: {
            this.uint32CountOfPage = input.readUInt32();
            break;
          }
        }
      }
    }
    
    public static Req_GetSongListByCategory parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Req_GetSongListByCategory(), data);
    }
    
    public static Req_GetSongListByCategory parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Req_GetSongListByCategory().mergeFrom(input);
    }
  }
  
  public static final class Resp_GetSongListByCategory extends
      com.google.protobuf.nano.MessageNano {
    
    private static volatile Resp_GetSongListByCategory[] _emptyArray;
    public static Resp_GetSongListByCategory[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Resp_GetSongListByCategory[0];
          }
        }
      }
      return _emptyArray;
    }
    
    // optional uint32 uint32_id = 1;
    public java.lang.Integer uint32Id;
    
    // repeated .com.txz.music_manager.MusicRecord rpt_music_list = 2;
    public com.txz.music_manager.MusicManager.MusicRecord[] rptMusicList;
    
    // optional uint32 uint32_total_count = 3;
    public java.lang.Integer uint32TotalCount;
    
    // optional uint32 uint32_page_no = 4;
    public java.lang.Integer uint32PageNo;
    
    // optional uint32 uint32_count_of_page = 5;
    public java.lang.Integer uint32CountOfPage;
    
    public Resp_GetSongListByCategory() {
      clear();
    }
    
    public Resp_GetSongListByCategory clear() {
      uint32Id = null;
      rptMusicList = com.txz.music_manager.MusicManager.MusicRecord.emptyArray();
      uint32TotalCount = null;
      uint32PageNo = null;
      uint32CountOfPage = null;
      cachedSize = -1;
      return this;
    }
    
    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.uint32Id != null) {
        output.writeUInt32(1, this.uint32Id);
      }
      if (this.rptMusicList != null && this.rptMusicList.length > 0) {
        for (int i = 0; i < this.rptMusicList.length; i++) {
          com.txz.music_manager.MusicManager.MusicRecord element = this.rptMusicList[i];
          if (element != null) {
            output.writeMessage(2, element);
          }
        }
      }
      if (this.uint32TotalCount != null) {
        output.writeUInt32(3, this.uint32TotalCount);
      }
      if (this.uint32PageNo != null) {
        output.writeUInt32(4, this.uint32PageNo);
      }
      if (this.uint32CountOfPage != null) {
        output.writeUInt32(5, this.uint32CountOfPage);
      }
      super.writeTo(output);
    }
    
    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.uint32Id != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(1, this.uint32Id);
      }
      if (this.rptMusicList != null && this.rptMusicList.length > 0) {
        for (int i = 0; i < this.rptMusicList.length; i++) {
          com.txz.music_manager.MusicManager.MusicRecord element = this.rptMusicList[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(2, element);
          }
        }
      }
      if (this.uint32TotalCount != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(3, this.uint32TotalCount);
      }
      if (this.uint32PageNo != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(4, this.uint32PageNo);
      }
      if (this.uint32CountOfPage != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(5, this.uint32CountOfPage);
      }
      return size;
    }
    
    @Override
    public Resp_GetSongListByCategory mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.uint32Id = input.readUInt32();
            break;
          }
          case 18: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 18);
            int i = this.rptMusicList == null ? 0 : this.rptMusicList.length;
            com.txz.music_manager.MusicManager.MusicRecord[] newArray =
                new com.txz.music_manager.MusicManager.MusicRecord[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.rptMusicList, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new com.txz.music_manager.MusicManager.MusicRecord();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new com.txz.music_manager.MusicManager.MusicRecord();
            input.readMessage(newArray[i]);
            this.rptMusicList = newArray;
            break;
          }
          case 24: {
            this.uint32TotalCount = input.readUInt32();
            break;
          }
          case 32: {
            this.uint32PageNo = input.readUInt32();
            break;
          }
          case 40: {
            this.uint32CountOfPage = input.readUInt32();
            break;
          }
        }
      }
    }
    
    public static Resp_GetSongListByCategory parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Resp_GetSongListByCategory(), data);
    }
    
    public static Resp_GetSongListByCategory parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Resp_GetSongListByCategory().mergeFrom(input);
    }
  }
  
  public static final class File_Category extends
      com.google.protobuf.nano.MessageNano {
    
    private static volatile File_Category[] _emptyArray;
    public static File_Category[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new File_Category[0];
          }
        }
      }
      return _emptyArray;
    }
    
    // optional .com.txz.music_manager.MusicCategory msg_category_info = 1;
    public com.txz.music_manager.MusicManager.MusicCategory msgCategoryInfo;
    
    // repeated .com.txz.music_manager.MusicRecord rpt_music_list = 2;
    public com.txz.music_manager.MusicManager.MusicRecord[] rptMusicList;
    
    public File_Category() {
      clear();
    }
    
    public File_Category clear() {
      msgCategoryInfo = null;
      rptMusicList = com.txz.music_manager.MusicManager.MusicRecord.emptyArray();
      cachedSize = -1;
      return this;
    }
    
    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.msgCategoryInfo != null) {
        output.writeMessage(1, this.msgCategoryInfo);
      }
      if (this.rptMusicList != null && this.rptMusicList.length > 0) {
        for (int i = 0; i < this.rptMusicList.length; i++) {
          com.txz.music_manager.MusicManager.MusicRecord element = this.rptMusicList[i];
          if (element != null) {
            output.writeMessage(2, element);
          }
        }
      }
      super.writeTo(output);
    }
    
    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.msgCategoryInfo != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.msgCategoryInfo);
      }
      if (this.rptMusicList != null && this.rptMusicList.length > 0) {
        for (int i = 0; i < this.rptMusicList.length; i++) {
          com.txz.music_manager.MusicManager.MusicRecord element = this.rptMusicList[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(2, element);
          }
        }
      }
      return size;
    }
    
    @Override
    public File_Category mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.msgCategoryInfo == null) {
              this.msgCategoryInfo = new com.txz.music_manager.MusicManager.MusicCategory();
            }
            input.readMessage(this.msgCategoryInfo);
            break;
          }
          case 18: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 18);
            int i = this.rptMusicList == null ? 0 : this.rptMusicList.length;
            com.txz.music_manager.MusicManager.MusicRecord[] newArray =
                new com.txz.music_manager.MusicManager.MusicRecord[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.rptMusicList, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new com.txz.music_manager.MusicManager.MusicRecord();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new com.txz.music_manager.MusicManager.MusicRecord();
            input.readMessage(newArray[i]);
            this.rptMusicList = newArray;
            break;
          }
        }
      }
    }
    
    public static File_Category parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new File_Category(), data);
    }
    
    public static File_Category parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new File_Category().mergeFrom(input);
    }
  }
  
  public static final class File_CategoryList extends
      com.google.protobuf.nano.MessageNano {
    
    private static volatile File_CategoryList[] _emptyArray;
    public static File_CategoryList[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new File_CategoryList[0];
          }
        }
      }
      return _emptyArray;
    }
    
    // repeated .com.txz.music_manager.File_Category rpt_category_list = 1;
    public com.txz.music_manager.MusicManager.File_Category[] rptCategoryList;
    
    public File_CategoryList() {
      clear();
    }
    
    public File_CategoryList clear() {
      rptCategoryList = com.txz.music_manager.MusicManager.File_Category.emptyArray();
      cachedSize = -1;
      return this;
    }
    
    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.rptCategoryList != null && this.rptCategoryList.length > 0) {
        for (int i = 0; i < this.rptCategoryList.length; i++) {
          com.txz.music_manager.MusicManager.File_Category element = this.rptCategoryList[i];
          if (element != null) {
            output.writeMessage(1, element);
          }
        }
      }
      super.writeTo(output);
    }
    
    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.rptCategoryList != null && this.rptCategoryList.length > 0) {
        for (int i = 0; i < this.rptCategoryList.length; i++) {
          com.txz.music_manager.MusicManager.File_Category element = this.rptCategoryList[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(1, element);
          }
        }
      }
      return size;
    }
    
    @Override
    public File_CategoryList mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 10);
            int i = this.rptCategoryList == null ? 0 : this.rptCategoryList.length;
            com.txz.music_manager.MusicManager.File_Category[] newArray =
                new com.txz.music_manager.MusicManager.File_Category[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.rptCategoryList, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new com.txz.music_manager.MusicManager.File_Category();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new com.txz.music_manager.MusicManager.File_Category();
            input.readMessage(newArray[i]);
            this.rptCategoryList = newArray;
            break;
          }
        }
      }
    }
    
    public static File_CategoryList parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new File_CategoryList(), data);
    }
    
    public static File_CategoryList parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new File_CategoryList().mergeFrom(input);
    }
  }
}
