// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.txz.ui.im;

@SuppressWarnings("hiding")
public interface UiIm {
  
  // enum SubEvent
  public static final int SUBEVENT_IM_ACTION_0 = 0;
  public static final int SUBEVENT_ACTION_ROOM_MEMBER_LIST_REQ = 1;
  public static final int SUBEVENT_ACTION_ROOM_MEMBER_LIST_RESP = 2;
  public static final int SUBEVENT_ACTION_ROOM_IN_REQ = 3;
  public static final int SUBEVENT_ACTION_ROOM_IN_RESP = 4;
  public static final int SUBEVENT_ACTION_ROOM_OUT_REQ = 5;
  public static final int SUBEVENT_ACTION_ROOM_OUT_RESP = 6;
  public static final int SUBEVENT_ACTION_ROOM_UPDATE_NOTIFY = 10;
  
  public static final class MemberInfo extends
      com.google.protobuf.nano.MessageNano {
    
    private static volatile MemberInfo[] _emptyArray;
    public static MemberInfo[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new MemberInfo[0];
          }
        }
      }
      return _emptyArray;
    }
    
    // optional string str_user_nick = 1;
    public java.lang.String strUserNick;
    
    // optional uint64 uint64_uid = 2;
    public java.lang.Long uint64Uid;
    
    // optional string str_face_url = 3;
    public java.lang.String strFaceUrl;
    
    public MemberInfo() {
      clear();
    }
    
    public MemberInfo clear() {
      strUserNick = null;
      uint64Uid = null;
      strFaceUrl = null;
      cachedSize = -1;
      return this;
    }
    
    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.strUserNick != null) {
        output.writeString(1, this.strUserNick);
      }
      if (this.uint64Uid != null) {
        output.writeUInt64(2, this.uint64Uid);
      }
      if (this.strFaceUrl != null) {
        output.writeString(3, this.strFaceUrl);
      }
      super.writeTo(output);
    }
    
    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.strUserNick != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.strUserNick);
      }
      if (this.uint64Uid != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt64Size(2, this.uint64Uid);
      }
      if (this.strFaceUrl != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(3, this.strFaceUrl);
      }
      return size;
    }
    
    @Override
    public MemberInfo mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.strUserNick = input.readString();
            break;
          }
          case 16: {
            this.uint64Uid = input.readUInt64();
            break;
          }
          case 26: {
            this.strFaceUrl = input.readString();
            break;
          }
        }
      }
    }
    
    public static MemberInfo parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new MemberInfo(), data);
    }
    
    public static MemberInfo parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new MemberInfo().mergeFrom(input);
    }
  }
  
  public static final class RoomMember extends
      com.google.protobuf.nano.MessageNano {
    
    private static volatile RoomMember[] _emptyArray;
    public static RoomMember[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new RoomMember[0];
          }
        }
      }
      return _emptyArray;
    }
    
    // optional uint32 uint32_target_distance = 1;
    public java.lang.Integer uint32TargetDistance;
    
    // optional .com.txz.ui.map.GpsInfo msg_gps = 2;
    public com.txz.ui.map.UiMap.GpsInfo msgGps;
    
    // optional .com.txz.ui.im.MemberInfo msg_info = 3;
    public com.txz.ui.im.UiIm.MemberInfo msgInfo;
    
    // optional uint32 uint32_target_time = 4;
    public java.lang.Integer uint32TargetTime;
    
    public RoomMember() {
      clear();
    }
    
    public RoomMember clear() {
      uint32TargetDistance = null;
      msgGps = null;
      msgInfo = null;
      uint32TargetTime = null;
      cachedSize = -1;
      return this;
    }
    
    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.uint32TargetDistance != null) {
        output.writeUInt32(1, this.uint32TargetDistance);
      }
      if (this.msgGps != null) {
        output.writeMessage(2, this.msgGps);
      }
      if (this.msgInfo != null) {
        output.writeMessage(3, this.msgInfo);
      }
      if (this.uint32TargetTime != null) {
        output.writeUInt32(4, this.uint32TargetTime);
      }
      super.writeTo(output);
    }
    
    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.uint32TargetDistance != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(1, this.uint32TargetDistance);
      }
      if (this.msgGps != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(2, this.msgGps);
      }
      if (this.msgInfo != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(3, this.msgInfo);
      }
      if (this.uint32TargetTime != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(4, this.uint32TargetTime);
      }
      return size;
    }
    
    @Override
    public RoomMember mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.uint32TargetDistance = input.readUInt32();
            break;
          }
          case 18: {
            if (this.msgGps == null) {
              this.msgGps = new com.txz.ui.map.UiMap.GpsInfo();
            }
            input.readMessage(this.msgGps);
            break;
          }
          case 26: {
            if (this.msgInfo == null) {
              this.msgInfo = new com.txz.ui.im.UiIm.MemberInfo();
            }
            input.readMessage(this.msgInfo);
            break;
          }
          case 32: {
            this.uint32TargetTime = input.readUInt32();
            break;
          }
        }
      }
    }
    
    public static RoomMember parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new RoomMember(), data);
    }
    
    public static RoomMember parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new RoomMember().mergeFrom(input);
    }
  }
  
  public static final class ActionRoomOut_Req extends
      com.google.protobuf.nano.MessageNano {
    
    private static volatile ActionRoomOut_Req[] _emptyArray;
    public static ActionRoomOut_Req[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new ActionRoomOut_Req[0];
          }
        }
      }
      return _emptyArray;
    }
    
    // optional uint32 uint32_from_type = 1;
    public java.lang.Integer uint32FromType;
    
    // optional uint64 uint64_rid = 2;
    public java.lang.Long uint64Rid;
    
    public ActionRoomOut_Req() {
      clear();
    }
    
    public ActionRoomOut_Req clear() {
      uint32FromType = null;
      uint64Rid = null;
      cachedSize = -1;
      return this;
    }
    
    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.uint32FromType != null) {
        output.writeUInt32(1, this.uint32FromType);
      }
      if (this.uint64Rid != null) {
        output.writeUInt64(2, this.uint64Rid);
      }
      super.writeTo(output);
    }
    
    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.uint32FromType != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(1, this.uint32FromType);
      }
      if (this.uint64Rid != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt64Size(2, this.uint64Rid);
      }
      return size;
    }
    
    @Override
    public ActionRoomOut_Req mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.uint32FromType = input.readUInt32();
            break;
          }
          case 16: {
            this.uint64Rid = input.readUInt64();
            break;
          }
        }
      }
    }
    
    public static ActionRoomOut_Req parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new ActionRoomOut_Req(), data);
    }
    
    public static ActionRoomOut_Req parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new ActionRoomOut_Req().mergeFrom(input);
    }
  }
  
  public static final class ActionRoomOut_Resp extends
      com.google.protobuf.nano.MessageNano {
    
    private static volatile ActionRoomOut_Resp[] _emptyArray;
    public static ActionRoomOut_Resp[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new ActionRoomOut_Resp[0];
          }
        }
      }
      return _emptyArray;
    }
    
    // optional uint32 uint32_from_type = 1;
    public java.lang.Integer uint32FromType;
    
    // optional uint64 uint64_rid = 2;
    public java.lang.Long uint64Rid;
    
    public ActionRoomOut_Resp() {
      clear();
    }
    
    public ActionRoomOut_Resp clear() {
      uint32FromType = null;
      uint64Rid = null;
      cachedSize = -1;
      return this;
    }
    
    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.uint32FromType != null) {
        output.writeUInt32(1, this.uint32FromType);
      }
      if (this.uint64Rid != null) {
        output.writeUInt64(2, this.uint64Rid);
      }
      super.writeTo(output);
    }
    
    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.uint32FromType != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(1, this.uint32FromType);
      }
      if (this.uint64Rid != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt64Size(2, this.uint64Rid);
      }
      return size;
    }
    
    @Override
    public ActionRoomOut_Resp mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.uint32FromType = input.readUInt32();
            break;
          }
          case 16: {
            this.uint64Rid = input.readUInt64();
            break;
          }
        }
      }
    }
    
    public static ActionRoomOut_Resp parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new ActionRoomOut_Resp(), data);
    }
    
    public static ActionRoomOut_Resp parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new ActionRoomOut_Resp().mergeFrom(input);
    }
  }
  
  public static final class ActionRoomIn_Req extends
      com.google.protobuf.nano.MessageNano {
    
    private static volatile ActionRoomIn_Req[] _emptyArray;
    public static ActionRoomIn_Req[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new ActionRoomIn_Req[0];
          }
        }
      }
      return _emptyArray;
    }
    
    // optional uint32 uint32_from_type = 1;
    public java.lang.Integer uint32FromType;
    
    // optional uint64 uint64_rid = 2;
    public java.lang.Long uint64Rid;
    
    // optional .com.txz.ui.im.RoomMember msg_user_info = 3;
    public com.txz.ui.im.UiIm.RoomMember msgUserInfo;
    
    public ActionRoomIn_Req() {
      clear();
    }
    
    public ActionRoomIn_Req clear() {
      uint32FromType = null;
      uint64Rid = null;
      msgUserInfo = null;
      cachedSize = -1;
      return this;
    }
    
    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.uint32FromType != null) {
        output.writeUInt32(1, this.uint32FromType);
      }
      if (this.uint64Rid != null) {
        output.writeUInt64(2, this.uint64Rid);
      }
      if (this.msgUserInfo != null) {
        output.writeMessage(3, this.msgUserInfo);
      }
      super.writeTo(output);
    }
    
    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.uint32FromType != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(1, this.uint32FromType);
      }
      if (this.uint64Rid != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt64Size(2, this.uint64Rid);
      }
      if (this.msgUserInfo != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(3, this.msgUserInfo);
      }
      return size;
    }
    
    @Override
    public ActionRoomIn_Req mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.uint32FromType = input.readUInt32();
            break;
          }
          case 16: {
            this.uint64Rid = input.readUInt64();
            break;
          }
          case 26: {
            if (this.msgUserInfo == null) {
              this.msgUserInfo = new com.txz.ui.im.UiIm.RoomMember();
            }
            input.readMessage(this.msgUserInfo);
            break;
          }
        }
      }
    }
    
    public static ActionRoomIn_Req parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new ActionRoomIn_Req(), data);
    }
    
    public static ActionRoomIn_Req parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new ActionRoomIn_Req().mergeFrom(input);
    }
  }
  
  public static final class ActionRoomIn_Resp extends
      com.google.protobuf.nano.MessageNano {
    
    private static volatile ActionRoomIn_Resp[] _emptyArray;
    public static ActionRoomIn_Resp[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new ActionRoomIn_Resp[0];
          }
        }
      }
      return _emptyArray;
    }
    
    // optional uint32 uint32_from_type = 1;
    public java.lang.Integer uint32FromType;
    
    // optional uint64 uint64_rid = 2;
    public java.lang.Long uint64Rid;
    
    public ActionRoomIn_Resp() {
      clear();
    }
    
    public ActionRoomIn_Resp clear() {
      uint32FromType = null;
      uint64Rid = null;
      cachedSize = -1;
      return this;
    }
    
    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.uint32FromType != null) {
        output.writeUInt32(1, this.uint32FromType);
      }
      if (this.uint64Rid != null) {
        output.writeUInt64(2, this.uint64Rid);
      }
      super.writeTo(output);
    }
    
    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.uint32FromType != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(1, this.uint32FromType);
      }
      if (this.uint64Rid != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt64Size(2, this.uint64Rid);
      }
      return size;
    }
    
    @Override
    public ActionRoomIn_Resp mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.uint32FromType = input.readUInt32();
            break;
          }
          case 16: {
            this.uint64Rid = input.readUInt64();
            break;
          }
        }
      }
    }
    
    public static ActionRoomIn_Resp parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new ActionRoomIn_Resp(), data);
    }
    
    public static ActionRoomIn_Resp parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new ActionRoomIn_Resp().mergeFrom(input);
    }
  }
  
  public static final class ActionRoomMemberList_Req extends
      com.google.protobuf.nano.MessageNano {
    
    private static volatile ActionRoomMemberList_Req[] _emptyArray;
    public static ActionRoomMemberList_Req[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new ActionRoomMemberList_Req[0];
          }
        }
      }
      return _emptyArray;
    }
    
    // optional uint64 uint64_rid = 1;
    public java.lang.Long uint64Rid;
    
    // optional uint32 uint32_type = 2;
    public java.lang.Integer uint32Type;
    
    // optional uint32 uint32_target_distance = 3;
    public java.lang.Integer uint32TargetDistance;
    
    // optional uint32 uint32_target_time = 4;
    public java.lang.Integer uint32TargetTime;
    
    public ActionRoomMemberList_Req() {
      clear();
    }
    
    public ActionRoomMemberList_Req clear() {
      uint64Rid = null;
      uint32Type = null;
      uint32TargetDistance = null;
      uint32TargetTime = null;
      cachedSize = -1;
      return this;
    }
    
    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.uint64Rid != null) {
        output.writeUInt64(1, this.uint64Rid);
      }
      if (this.uint32Type != null) {
        output.writeUInt32(2, this.uint32Type);
      }
      if (this.uint32TargetDistance != null) {
        output.writeUInt32(3, this.uint32TargetDistance);
      }
      if (this.uint32TargetTime != null) {
        output.writeUInt32(4, this.uint32TargetTime);
      }
      super.writeTo(output);
    }
    
    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.uint64Rid != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt64Size(1, this.uint64Rid);
      }
      if (this.uint32Type != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(2, this.uint32Type);
      }
      if (this.uint32TargetDistance != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(3, this.uint32TargetDistance);
      }
      if (this.uint32TargetTime != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(4, this.uint32TargetTime);
      }
      return size;
    }
    
    @Override
    public ActionRoomMemberList_Req mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.uint64Rid = input.readUInt64();
            break;
          }
          case 16: {
            this.uint32Type = input.readUInt32();
            break;
          }
          case 24: {
            this.uint32TargetDistance = input.readUInt32();
            break;
          }
          case 32: {
            this.uint32TargetTime = input.readUInt32();
            break;
          }
        }
      }
    }
    
    public static ActionRoomMemberList_Req parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new ActionRoomMemberList_Req(), data);
    }
    
    public static ActionRoomMemberList_Req parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new ActionRoomMemberList_Req().mergeFrom(input);
    }
  }
  
  public static final class ActionRoomMemberList_Resp extends
      com.google.protobuf.nano.MessageNano {
    
    private static volatile ActionRoomMemberList_Resp[] _emptyArray;
    public static ActionRoomMemberList_Resp[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new ActionRoomMemberList_Resp[0];
          }
        }
      }
      return _emptyArray;
    }
    
    // optional uint64 uint64_rid = 1;
    public java.lang.Long uint64Rid;
    
    // optional uint32 uint32_type = 2;
    public java.lang.Integer uint32Type;
    
    // repeated .com.txz.ui.im.RoomMember rpt_msg_member_list = 3;
    public com.txz.ui.im.UiIm.RoomMember[] rptMsgMemberList;
    
    public ActionRoomMemberList_Resp() {
      clear();
    }
    
    public ActionRoomMemberList_Resp clear() {
      uint64Rid = null;
      uint32Type = null;
      rptMsgMemberList = com.txz.ui.im.UiIm.RoomMember.emptyArray();
      cachedSize = -1;
      return this;
    }
    
    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.uint64Rid != null) {
        output.writeUInt64(1, this.uint64Rid);
      }
      if (this.uint32Type != null) {
        output.writeUInt32(2, this.uint32Type);
      }
      if (this.rptMsgMemberList != null && this.rptMsgMemberList.length > 0) {
        for (int i = 0; i < this.rptMsgMemberList.length; i++) {
          com.txz.ui.im.UiIm.RoomMember element = this.rptMsgMemberList[i];
          if (element != null) {
            output.writeMessage(3, element);
          }
        }
      }
      super.writeTo(output);
    }
    
    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.uint64Rid != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt64Size(1, this.uint64Rid);
      }
      if (this.uint32Type != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(2, this.uint32Type);
      }
      if (this.rptMsgMemberList != null && this.rptMsgMemberList.length > 0) {
        for (int i = 0; i < this.rptMsgMemberList.length; i++) {
          com.txz.ui.im.UiIm.RoomMember element = this.rptMsgMemberList[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(3, element);
          }
        }
      }
      return size;
    }
    
    @Override
    public ActionRoomMemberList_Resp mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.uint64Rid = input.readUInt64();
            break;
          }
          case 16: {
            this.uint32Type = input.readUInt32();
            break;
          }
          case 26: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 26);
            int i = this.rptMsgMemberList == null ? 0 : this.rptMsgMemberList.length;
            com.txz.ui.im.UiIm.RoomMember[] newArray =
                new com.txz.ui.im.UiIm.RoomMember[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.rptMsgMemberList, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new com.txz.ui.im.UiIm.RoomMember();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new com.txz.ui.im.UiIm.RoomMember();
            input.readMessage(newArray[i]);
            this.rptMsgMemberList = newArray;
            break;
          }
        }
      }
    }
    
    public static ActionRoomMemberList_Resp parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new ActionRoomMemberList_Resp(), data);
    }
    
    public static ActionRoomMemberList_Resp parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new ActionRoomMemberList_Resp().mergeFrom(input);
    }
  }
  
  public static final class ActionRoomUpdateNotify extends
      com.google.protobuf.nano.MessageNano {
    
    private static volatile ActionRoomUpdateNotify[] _emptyArray;
    public static ActionRoomUpdateNotify[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new ActionRoomUpdateNotify[0];
          }
        }
      }
      return _emptyArray;
    }
    
    // repeated .com.txz.ui.im.RoomMember rpt_msg_user_in_list = 1;
    public com.txz.ui.im.UiIm.RoomMember[] rptMsgUserInList;
    
    // repeated uint64 rpt_uint64_user_out_list = 2;
    public long[] rptUint64UserOutList;
    
    public ActionRoomUpdateNotify() {
      clear();
    }
    
    public ActionRoomUpdateNotify clear() {
      rptMsgUserInList = com.txz.ui.im.UiIm.RoomMember.emptyArray();
      rptUint64UserOutList = com.google.protobuf.nano.WireFormatNano.EMPTY_LONG_ARRAY;
      cachedSize = -1;
      return this;
    }
    
    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.rptMsgUserInList != null && this.rptMsgUserInList.length > 0) {
        for (int i = 0; i < this.rptMsgUserInList.length; i++) {
          com.txz.ui.im.UiIm.RoomMember element = this.rptMsgUserInList[i];
          if (element != null) {
            output.writeMessage(1, element);
          }
        }
      }
      if (this.rptUint64UserOutList != null && this.rptUint64UserOutList.length > 0) {
        for (int i = 0; i < this.rptUint64UserOutList.length; i++) {
          output.writeUInt64(2, this.rptUint64UserOutList[i]);
        }
      }
      super.writeTo(output);
    }
    
    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.rptMsgUserInList != null && this.rptMsgUserInList.length > 0) {
        for (int i = 0; i < this.rptMsgUserInList.length; i++) {
          com.txz.ui.im.UiIm.RoomMember element = this.rptMsgUserInList[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(1, element);
          }
        }
      }
      if (this.rptUint64UserOutList != null && this.rptUint64UserOutList.length > 0) {
        int dataSize = 0;
        for (int i = 0; i < this.rptUint64UserOutList.length; i++) {
          long element = this.rptUint64UserOutList[i];
          dataSize += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeUInt64SizeNoTag(element);
        }
        size += dataSize;
        size += 1 * this.rptUint64UserOutList.length;
      }
      return size;
    }
    
    @Override
    public ActionRoomUpdateNotify mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 10);
            int i = this.rptMsgUserInList == null ? 0 : this.rptMsgUserInList.length;
            com.txz.ui.im.UiIm.RoomMember[] newArray =
                new com.txz.ui.im.UiIm.RoomMember[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.rptMsgUserInList, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new com.txz.ui.im.UiIm.RoomMember();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new com.txz.ui.im.UiIm.RoomMember();
            input.readMessage(newArray[i]);
            this.rptMsgUserInList = newArray;
            break;
          }
          case 16: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 16);
            int i = this.rptUint64UserOutList == null ? 0 : this.rptUint64UserOutList.length;
            long[] newArray = new long[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.rptUint64UserOutList, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = input.readUInt64();
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = input.readUInt64();
            this.rptUint64UserOutList = newArray;
            break;
          }
          case 18: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            // First pass to compute array length.
            int arrayLength = 0;
            int startPos = input.getPosition();
            while (input.getBytesUntilLimit() > 0) {
              input.readUInt64();
              arrayLength++;
            }
            input.rewindToPosition(startPos);
            int i = this.rptUint64UserOutList == null ? 0 : this.rptUint64UserOutList.length;
            long[] newArray = new long[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.rptUint64UserOutList, 0, newArray, 0, i);
            }
            for (; i < newArray.length; i++) {
              newArray[i] = input.readUInt64();
            }
            this.rptUint64UserOutList = newArray;
            input.popLimit(limit);
            break;
          }
        }
      }
    }
    
    public static ActionRoomUpdateNotify parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new ActionRoomUpdateNotify(), data);
    }
    
    public static ActionRoomUpdateNotify parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new ActionRoomUpdateNotify().mergeFrom(input);
    }
  }
  
  public static final class MapNaviPath extends
      com.google.protobuf.nano.MessageNano {
    
    private static volatile MapNaviPath[] _emptyArray;
    public static MapNaviPath[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new MapNaviPath[0];
          }
        }
      }
      return _emptyArray;
    }
    
    // optional uint32 uint32_all_length = 1;
    public java.lang.Integer uint32AllLength;
    
    // optional uint32 uint32_all_time = 2;
    public java.lang.Integer uint32AllTime;
    
    // optional .com.txz.ui.map.GpsInfo msg_bounds_northeast = 3;
    public com.txz.ui.map.UiMap.GpsInfo msgBoundsNortheast;
    
    // optional .com.txz.ui.map.GpsInfo msg_bounds_southwest = 4;
    public com.txz.ui.map.UiMap.GpsInfo msgBoundsSouthwest;
    
    // optional .com.txz.ui.map.GpsInfo msg_center = 5;
    public com.txz.ui.map.UiMap.GpsInfo msgCenter;
    
    // optional .com.txz.ui.map.GpsInfo msg_start = 6;
    public com.txz.ui.map.UiMap.GpsInfo msgStart;
    
    // optional .com.txz.ui.map.GpsInfo msg_end = 7;
    public com.txz.ui.map.UiMap.GpsInfo msgEnd;
    
    // repeated .com.txz.ui.map.GpsInfo msg_points = 8;
    public com.txz.ui.map.UiMap.GpsInfo[] msgPoints;
    
    // optional uint32 uint32_steps_count = 9;
    public java.lang.Integer uint32StepsCount;
    
    // optional uint32 uint32_strategy = 10;
    public java.lang.Integer uint32Strategy;
    
    // optional uint32 uint32_total_cost = 11;
    public java.lang.Integer uint32TotalCost;
    
    public MapNaviPath() {
      clear();
    }
    
    public MapNaviPath clear() {
      uint32AllLength = null;
      uint32AllTime = null;
      msgBoundsNortheast = null;
      msgBoundsSouthwest = null;
      msgCenter = null;
      msgStart = null;
      msgEnd = null;
      msgPoints = com.txz.ui.map.UiMap.GpsInfo.emptyArray();
      uint32StepsCount = null;
      uint32Strategy = null;
      uint32TotalCost = null;
      cachedSize = -1;
      return this;
    }
    
    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.uint32AllLength != null) {
        output.writeUInt32(1, this.uint32AllLength);
      }
      if (this.uint32AllTime != null) {
        output.writeUInt32(2, this.uint32AllTime);
      }
      if (this.msgBoundsNortheast != null) {
        output.writeMessage(3, this.msgBoundsNortheast);
      }
      if (this.msgBoundsSouthwest != null) {
        output.writeMessage(4, this.msgBoundsSouthwest);
      }
      if (this.msgCenter != null) {
        output.writeMessage(5, this.msgCenter);
      }
      if (this.msgStart != null) {
        output.writeMessage(6, this.msgStart);
      }
      if (this.msgEnd != null) {
        output.writeMessage(7, this.msgEnd);
      }
      if (this.msgPoints != null && this.msgPoints.length > 0) {
        for (int i = 0; i < this.msgPoints.length; i++) {
          com.txz.ui.map.UiMap.GpsInfo element = this.msgPoints[i];
          if (element != null) {
            output.writeMessage(8, element);
          }
        }
      }
      if (this.uint32StepsCount != null) {
        output.writeUInt32(9, this.uint32StepsCount);
      }
      if (this.uint32Strategy != null) {
        output.writeUInt32(10, this.uint32Strategy);
      }
      if (this.uint32TotalCost != null) {
        output.writeUInt32(11, this.uint32TotalCost);
      }
      super.writeTo(output);
    }
    
    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.uint32AllLength != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(1, this.uint32AllLength);
      }
      if (this.uint32AllTime != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(2, this.uint32AllTime);
      }
      if (this.msgBoundsNortheast != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(3, this.msgBoundsNortheast);
      }
      if (this.msgBoundsSouthwest != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(4, this.msgBoundsSouthwest);
      }
      if (this.msgCenter != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(5, this.msgCenter);
      }
      if (this.msgStart != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(6, this.msgStart);
      }
      if (this.msgEnd != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(7, this.msgEnd);
      }
      if (this.msgPoints != null && this.msgPoints.length > 0) {
        for (int i = 0; i < this.msgPoints.length; i++) {
          com.txz.ui.map.UiMap.GpsInfo element = this.msgPoints[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(8, element);
          }
        }
      }
      if (this.uint32StepsCount != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(9, this.uint32StepsCount);
      }
      if (this.uint32Strategy != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(10, this.uint32Strategy);
      }
      if (this.uint32TotalCost != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(11, this.uint32TotalCost);
      }
      return size;
    }
    
    @Override
    public MapNaviPath mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.uint32AllLength = input.readUInt32();
            break;
          }
          case 16: {
            this.uint32AllTime = input.readUInt32();
            break;
          }
          case 26: {
            if (this.msgBoundsNortheast == null) {
              this.msgBoundsNortheast = new com.txz.ui.map.UiMap.GpsInfo();
            }
            input.readMessage(this.msgBoundsNortheast);
            break;
          }
          case 34: {
            if (this.msgBoundsSouthwest == null) {
              this.msgBoundsSouthwest = new com.txz.ui.map.UiMap.GpsInfo();
            }
            input.readMessage(this.msgBoundsSouthwest);
            break;
          }
          case 42: {
            if (this.msgCenter == null) {
              this.msgCenter = new com.txz.ui.map.UiMap.GpsInfo();
            }
            input.readMessage(this.msgCenter);
            break;
          }
          case 50: {
            if (this.msgStart == null) {
              this.msgStart = new com.txz.ui.map.UiMap.GpsInfo();
            }
            input.readMessage(this.msgStart);
            break;
          }
          case 58: {
            if (this.msgEnd == null) {
              this.msgEnd = new com.txz.ui.map.UiMap.GpsInfo();
            }
            input.readMessage(this.msgEnd);
            break;
          }
          case 66: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 66);
            int i = this.msgPoints == null ? 0 : this.msgPoints.length;
            com.txz.ui.map.UiMap.GpsInfo[] newArray =
                new com.txz.ui.map.UiMap.GpsInfo[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.msgPoints, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new com.txz.ui.map.UiMap.GpsInfo();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new com.txz.ui.map.UiMap.GpsInfo();
            input.readMessage(newArray[i]);
            this.msgPoints = newArray;
            break;
          }
          case 72: {
            this.uint32StepsCount = input.readUInt32();
            break;
          }
          case 80: {
            this.uint32Strategy = input.readUInt32();
            break;
          }
          case 88: {
            this.uint32TotalCost = input.readUInt32();
            break;
          }
        }
      }
    }
    
    public static MapNaviPath parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new MapNaviPath(), data);
    }
    
    public static MapNaviPath parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new MapNaviPath().mergeFrom(input);
    }
  }
}
