// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.txz.asr.udp;

@SuppressWarnings("hiding")
public interface TxzAsrUdpProtosV0 {
  
  // enum TxzAsrUdpEncodeType
  public static final int ENCODE_TYPE_DEFAULT = 0;
  public static final int ENCODE_TYPE_GZIP = 1;
  
  // enum TxzAsrUdpLanguageType
  public static final int DIALECT_TYPE_CHINESE = 0;
  public static final int DIALECT_TYPE_ENGLISH = 1;
  
  // enum TxzAsrUdpSceneType
  public static final int SCENE_TYPE_DEFAULT = 0;
  public static final int SCENE_TYPE_WECHAT_RECORD = 1;
  public static final int SCENE_TYPE_NAV = 2;
  public static final int SCENE_TYPE_MUSIC = 3;
  public static final int SCENE_TYPE_UPLOAD_DICT = 99;
  
  // enum TxzAsrUdpDialectType
  public static final int DIALECT_TYPE_PUTONGHUA = 0;
  public static final int DIALECT_TYPE_CANTONESE = 1;
  
  // enum TxzAsrUdpPcmSamplingRate
  public static final int PCM_SAMPLING_RATE_DEFAULT = 0;
  public static final int PCM_SAMPLING_RATE_8K = 1;
  public static final int PCM_SAMPLING_RATE_16K = 2;
  
  // enum TxzAsrUdpVoiceSaveType
  public static final int VOICE_SAVE_TYPE_DEFAULT = 0;
  public static final int VOICE_SAVE_TYPE_URL = 1;
  
  // enum SemantemeVersion
  public static final int SEMANTEME_VERSION_DEFAULT = 0;
  public static final int SEMANTEME_VERSION_JSON_1 = 1;
  
  public static final class TxzAsrUdpAck extends
      com.google.protobuf.nano.MessageNano {
    
    private static volatile TxzAsrUdpAck[] _emptyArray;
    public static TxzAsrUdpAck[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new TxzAsrUdpAck[0];
          }
        }
      }
      return _emptyArray;
    }
    
    // optional uint32 uint32_seq = 1;
    public java.lang.Integer uint32Seq;
    
    // optional uint32 uint32_pkg_type = 2;
    public java.lang.Integer uint32PkgType;
    
    public TxzAsrUdpAck() {
      clear();
    }
    
    public TxzAsrUdpAck clear() {
      uint32Seq = null;
      uint32PkgType = null;
      cachedSize = -1;
      return this;
    }
    
    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.uint32Seq != null) {
        output.writeUInt32(1, this.uint32Seq);
      }
      if (this.uint32PkgType != null) {
        output.writeUInt32(2, this.uint32PkgType);
      }
      super.writeTo(output);
    }
    
    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.uint32Seq != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(1, this.uint32Seq);
      }
      if (this.uint32PkgType != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(2, this.uint32PkgType);
      }
      return size;
    }
    
    @Override
    public TxzAsrUdpAck mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.uint32Seq = input.readUInt32();
            break;
          }
          case 16: {
            this.uint32PkgType = input.readUInt32();
            break;
          }
        }
      }
    }
    
    public static TxzAsrUdpAck parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new TxzAsrUdpAck(), data);
    }
    
    public static TxzAsrUdpAck parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new TxzAsrUdpAck().mergeFrom(input);
    }
  }
  
  public static final class TxzAsrUdpAsrParam extends
      com.google.protobuf.nano.MessageNano {
    
    private static volatile TxzAsrUdpAsrParam[] _emptyArray;
    public static TxzAsrUdpAsrParam[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new TxzAsrUdpAsrParam[0];
          }
        }
      }
      return _emptyArray;
    }
    
    // optional uint32 uint32_language_type = 1;
    public java.lang.Integer uint32LanguageType;
    
    // optional uint32 uint32_dialect_type = 2;
    public java.lang.Integer uint32DialectType;
    
    // optional uint32 uint32_bos = 3;
    public java.lang.Integer uint32Bos;
    
    // optional uint32 uint32_aos = 4;
    public java.lang.Integer uint32Aos;
    
    // optional uint32 uint32_max_speech_time = 5;
    public java.lang.Integer uint32MaxSpeechTime;
    
    // optional uint32 uint32_pcm_format = 6;
    public java.lang.Integer uint32PcmFormat;
    
    public TxzAsrUdpAsrParam() {
      clear();
    }
    
    public TxzAsrUdpAsrParam clear() {
      uint32LanguageType = null;
      uint32DialectType = null;
      uint32Bos = null;
      uint32Aos = null;
      uint32MaxSpeechTime = null;
      uint32PcmFormat = null;
      cachedSize = -1;
      return this;
    }
    
    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.uint32LanguageType != null) {
        output.writeUInt32(1, this.uint32LanguageType);
      }
      if (this.uint32DialectType != null) {
        output.writeUInt32(2, this.uint32DialectType);
      }
      if (this.uint32Bos != null) {
        output.writeUInt32(3, this.uint32Bos);
      }
      if (this.uint32Aos != null) {
        output.writeUInt32(4, this.uint32Aos);
      }
      if (this.uint32MaxSpeechTime != null) {
        output.writeUInt32(5, this.uint32MaxSpeechTime);
      }
      if (this.uint32PcmFormat != null) {
        output.writeUInt32(6, this.uint32PcmFormat);
      }
      super.writeTo(output);
    }
    
    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.uint32LanguageType != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(1, this.uint32LanguageType);
      }
      if (this.uint32DialectType != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(2, this.uint32DialectType);
      }
      if (this.uint32Bos != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(3, this.uint32Bos);
      }
      if (this.uint32Aos != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(4, this.uint32Aos);
      }
      if (this.uint32MaxSpeechTime != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(5, this.uint32MaxSpeechTime);
      }
      if (this.uint32PcmFormat != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(6, this.uint32PcmFormat);
      }
      return size;
    }
    
    @Override
    public TxzAsrUdpAsrParam mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.uint32LanguageType = input.readUInt32();
            break;
          }
          case 16: {
            this.uint32DialectType = input.readUInt32();
            break;
          }
          case 24: {
            this.uint32Bos = input.readUInt32();
            break;
          }
          case 32: {
            this.uint32Aos = input.readUInt32();
            break;
          }
          case 40: {
            this.uint32MaxSpeechTime = input.readUInt32();
            break;
          }
          case 48: {
            this.uint32PcmFormat = input.readUInt32();
            break;
          }
        }
      }
    }
    
    public static TxzAsrUdpAsrParam parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new TxzAsrUdpAsrParam(), data);
    }
    
    public static TxzAsrUdpAsrParam parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new TxzAsrUdpAsrParam().mergeFrom(input);
    }
  }
  
  public static final class TxzAsrUdpNlpParam extends
      com.google.protobuf.nano.MessageNano {
    
    private static volatile TxzAsrUdpNlpParam[] _emptyArray;
    public static TxzAsrUdpNlpParam[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new TxzAsrUdpNlpParam[0];
          }
        }
      }
      return _emptyArray;
    }
    
    public TxzAsrUdpNlpParam() {
      clear();
    }
    
    public TxzAsrUdpNlpParam clear() {
      cachedSize = -1;
      return this;
    }
    
    @Override
    public TxzAsrUdpNlpParam mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
        }
      }
    }
    
    public static TxzAsrUdpNlpParam parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new TxzAsrUdpNlpParam(), data);
    }
    
    public static TxzAsrUdpNlpParam parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new TxzAsrUdpNlpParam().mergeFrom(input);
    }
  }
  
  public static final class TxzAsrUdpBaseInfo extends
      com.google.protobuf.nano.MessageNano {
    
    private static volatile TxzAsrUdpBaseInfo[] _emptyArray;
    public static TxzAsrUdpBaseInfo[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new TxzAsrUdpBaseInfo[0];
          }
        }
      }
      return _emptyArray;
    }
    
    // optional uint32 uint32_encode_type = 1;
    public java.lang.Integer uint32EncodeType;
    
    // optional uint32 uint32_context_id = 2;
    public java.lang.Integer uint32ContextId;
    
    // optional uint32 uint32_scene_type = 3;
    public java.lang.Integer uint32SceneType;
    
    // optional uint32 uint32_semanteme_version = 4;
    public java.lang.Integer uint32SemantemeVersion;
    
    // optional .com.txz.asr.udp.TxzAsrUdpAsrParam msg_asr_param = 5;
    public com.txz.asr.udp.TxzAsrUdpProtosV0.TxzAsrUdpAsrParam msgAsrParam;
    
    // optional .com.txz.asr.udp.TxzAsrUdpNlpParam msg_nlp_param = 6;
    public com.txz.asr.udp.TxzAsrUdpProtosV0.TxzAsrUdpNlpParam msgNlpParam;
    
    // optional uint32 uint32_voice_save_type = 7;
    public java.lang.Integer uint32VoiceSaveType;
    
    public TxzAsrUdpBaseInfo() {
      clear();
    }
    
    public TxzAsrUdpBaseInfo clear() {
      uint32EncodeType = null;
      uint32ContextId = null;
      uint32SceneType = null;
      uint32SemantemeVersion = null;
      msgAsrParam = null;
      msgNlpParam = null;
      uint32VoiceSaveType = null;
      cachedSize = -1;
      return this;
    }
    
    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.uint32EncodeType != null) {
        output.writeUInt32(1, this.uint32EncodeType);
      }
      if (this.uint32ContextId != null) {
        output.writeUInt32(2, this.uint32ContextId);
      }
      if (this.uint32SceneType != null) {
        output.writeUInt32(3, this.uint32SceneType);
      }
      if (this.uint32SemantemeVersion != null) {
        output.writeUInt32(4, this.uint32SemantemeVersion);
      }
      if (this.msgAsrParam != null) {
        output.writeMessage(5, this.msgAsrParam);
      }
      if (this.msgNlpParam != null) {
        output.writeMessage(6, this.msgNlpParam);
      }
      if (this.uint32VoiceSaveType != null) {
        output.writeUInt32(7, this.uint32VoiceSaveType);
      }
      super.writeTo(output);
    }
    
    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.uint32EncodeType != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(1, this.uint32EncodeType);
      }
      if (this.uint32ContextId != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(2, this.uint32ContextId);
      }
      if (this.uint32SceneType != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(3, this.uint32SceneType);
      }
      if (this.uint32SemantemeVersion != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(4, this.uint32SemantemeVersion);
      }
      if (this.msgAsrParam != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(5, this.msgAsrParam);
      }
      if (this.msgNlpParam != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(6, this.msgNlpParam);
      }
      if (this.uint32VoiceSaveType != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(7, this.uint32VoiceSaveType);
      }
      return size;
    }
    
    @Override
    public TxzAsrUdpBaseInfo mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.uint32EncodeType = input.readUInt32();
            break;
          }
          case 16: {
            this.uint32ContextId = input.readUInt32();
            break;
          }
          case 24: {
            this.uint32SceneType = input.readUInt32();
            break;
          }
          case 32: {
            this.uint32SemantemeVersion = input.readUInt32();
            break;
          }
          case 42: {
            if (this.msgAsrParam == null) {
              this.msgAsrParam = new com.txz.asr.udp.TxzAsrUdpProtosV0.TxzAsrUdpAsrParam();
            }
            input.readMessage(this.msgAsrParam);
            break;
          }
          case 50: {
            if (this.msgNlpParam == null) {
              this.msgNlpParam = new com.txz.asr.udp.TxzAsrUdpProtosV0.TxzAsrUdpNlpParam();
            }
            input.readMessage(this.msgNlpParam);
            break;
          }
          case 56: {
            this.uint32VoiceSaveType = input.readUInt32();
            break;
          }
        }
      }
    }
    
    public static TxzAsrUdpBaseInfo parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new TxzAsrUdpBaseInfo(), data);
    }
    
    public static TxzAsrUdpBaseInfo parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new TxzAsrUdpBaseInfo().mergeFrom(input);
    }
  }
  
  public static final class TxzAsrUdpExtendInfo extends
      com.google.protobuf.nano.MessageNano {
    
    private static volatile TxzAsrUdpExtendInfo[] _emptyArray;
    public static TxzAsrUdpExtendInfo[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new TxzAsrUdpExtendInfo[0];
          }
        }
      }
      return _emptyArray;
    }
    
    // optional double dbl_lat = 1;
    public java.lang.Double dblLat;
    
    // optional double dbl_lng = 2;
    public java.lang.Double dblLng;
    
    // optional bytes str_city = 3;
    public byte[] strCity;
    
    public TxzAsrUdpExtendInfo() {
      clear();
    }
    
    public TxzAsrUdpExtendInfo clear() {
      dblLat = null;
      dblLng = null;
      strCity = null;
      cachedSize = -1;
      return this;
    }
    
    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.dblLat != null) {
        output.writeDouble(1, this.dblLat);
      }
      if (this.dblLng != null) {
        output.writeDouble(2, this.dblLng);
      }
      if (this.strCity != null) {
        output.writeBytes(3, this.strCity);
      }
      super.writeTo(output);
    }
    
    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.dblLat != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeDoubleSize(1, this.dblLat);
      }
      if (this.dblLng != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeDoubleSize(2, this.dblLng);
      }
      if (this.strCity != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBytesSize(3, this.strCity);
      }
      return size;
    }
    
    @Override
    public TxzAsrUdpExtendInfo mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 9: {
            this.dblLat = input.readDouble();
            break;
          }
          case 17: {
            this.dblLng = input.readDouble();
            break;
          }
          case 26: {
            this.strCity = input.readBytes();
            break;
          }
        }
      }
    }
    
    public static TxzAsrUdpExtendInfo parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new TxzAsrUdpExtendInfo(), data);
    }
    
    public static TxzAsrUdpExtendInfo parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new TxzAsrUdpExtendInfo().mergeFrom(input);
    }
  }
  
  public static final class TxzAsrUdpInfo extends
      com.google.protobuf.nano.MessageNano {
    
    private static volatile TxzAsrUdpInfo[] _emptyArray;
    public static TxzAsrUdpInfo[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new TxzAsrUdpInfo[0];
          }
        }
      }
      return _emptyArray;
    }
    
    // optional .com.txz.asr.udp.TxzAsrUdpBaseInfo msg_base_info = 1;
    public com.txz.asr.udp.TxzAsrUdpProtosV0.TxzAsrUdpBaseInfo msgBaseInfo;
    
    // optional .com.txz.asr.udp.TxzAsrUdpExtendInfo msg_extend_info = 2;
    public com.txz.asr.udp.TxzAsrUdpProtosV0.TxzAsrUdpExtendInfo msgExtendInfo;
    
    public TxzAsrUdpInfo() {
      clear();
    }
    
    public TxzAsrUdpInfo clear() {
      msgBaseInfo = null;
      msgExtendInfo = null;
      cachedSize = -1;
      return this;
    }
    
    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.msgBaseInfo != null) {
        output.writeMessage(1, this.msgBaseInfo);
      }
      if (this.msgExtendInfo != null) {
        output.writeMessage(2, this.msgExtendInfo);
      }
      super.writeTo(output);
    }
    
    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.msgBaseInfo != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.msgBaseInfo);
      }
      if (this.msgExtendInfo != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(2, this.msgExtendInfo);
      }
      return size;
    }
    
    @Override
    public TxzAsrUdpInfo mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.msgBaseInfo == null) {
              this.msgBaseInfo = new com.txz.asr.udp.TxzAsrUdpProtosV0.TxzAsrUdpBaseInfo();
            }
            input.readMessage(this.msgBaseInfo);
            break;
          }
          case 18: {
            if (this.msgExtendInfo == null) {
              this.msgExtendInfo = new com.txz.asr.udp.TxzAsrUdpProtosV0.TxzAsrUdpExtendInfo();
            }
            input.readMessage(this.msgExtendInfo);
            break;
          }
        }
      }
    }
    
    public static TxzAsrUdpInfo parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new TxzAsrUdpInfo(), data);
    }
    
    public static TxzAsrUdpInfo parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new TxzAsrUdpInfo().mergeFrom(input);
    }
  }
  
  public static final class TxzAsrUdpData extends
      com.google.protobuf.nano.MessageNano {
    
    private static volatile TxzAsrUdpData[] _emptyArray;
    public static TxzAsrUdpData[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new TxzAsrUdpData[0];
          }
        }
      }
      return _emptyArray;
    }
    
    // optional uint32 uint32_pkg_id = 1;
    public java.lang.Integer uint32PkgId;
    
    // optional uint32 uint32_frame_info = 2;
    public java.lang.Integer uint32FrameInfo;
    
    // optional bytes str_frame_data = 3;
    public byte[] strFrameData;
    
    public TxzAsrUdpData() {
      clear();
    }
    
    public TxzAsrUdpData clear() {
      uint32PkgId = null;
      uint32FrameInfo = null;
      strFrameData = null;
      cachedSize = -1;
      return this;
    }
    
    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.uint32PkgId != null) {
        output.writeUInt32(1, this.uint32PkgId);
      }
      if (this.uint32FrameInfo != null) {
        output.writeUInt32(2, this.uint32FrameInfo);
      }
      if (this.strFrameData != null) {
        output.writeBytes(3, this.strFrameData);
      }
      super.writeTo(output);
    }
    
    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.uint32PkgId != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(1, this.uint32PkgId);
      }
      if (this.uint32FrameInfo != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(2, this.uint32FrameInfo);
      }
      if (this.strFrameData != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBytesSize(3, this.strFrameData);
      }
      return size;
    }
    
    @Override
    public TxzAsrUdpData mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.uint32PkgId = input.readUInt32();
            break;
          }
          case 16: {
            this.uint32FrameInfo = input.readUInt32();
            break;
          }
          case 26: {
            this.strFrameData = input.readBytes();
            break;
          }
        }
      }
    }
    
    public static TxzAsrUdpData parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new TxzAsrUdpData(), data);
    }
    
    public static TxzAsrUdpData parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new TxzAsrUdpData().mergeFrom(input);
    }
  }
  
  public static final class TxzAsrUdpComplete extends
      com.google.protobuf.nano.MessageNano {
    
    private static volatile TxzAsrUdpComplete[] _emptyArray;
    public static TxzAsrUdpComplete[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new TxzAsrUdpComplete[0];
          }
        }
      }
      return _emptyArray;
    }
    
    // optional uint32 uint32_last_pkg_id = 1;
    public java.lang.Integer uint32LastPkgId;
    
    public TxzAsrUdpComplete() {
      clear();
    }
    
    public TxzAsrUdpComplete clear() {
      uint32LastPkgId = null;
      cachedSize = -1;
      return this;
    }
    
    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.uint32LastPkgId != null) {
        output.writeUInt32(1, this.uint32LastPkgId);
      }
      super.writeTo(output);
    }
    
    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.uint32LastPkgId != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(1, this.uint32LastPkgId);
      }
      return size;
    }
    
    @Override
    public TxzAsrUdpComplete mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.uint32LastPkgId = input.readUInt32();
            break;
          }
        }
      }
    }
    
    public static TxzAsrUdpComplete parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new TxzAsrUdpComplete(), data);
    }
    
    public static TxzAsrUdpComplete parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new TxzAsrUdpComplete().mergeFrom(input);
    }
  }
  
  public static final class TxzAsrUdpCancel extends
      com.google.protobuf.nano.MessageNano {
    
    private static volatile TxzAsrUdpCancel[] _emptyArray;
    public static TxzAsrUdpCancel[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new TxzAsrUdpCancel[0];
          }
        }
      }
      return _emptyArray;
    }
    
    public TxzAsrUdpCancel() {
      clear();
    }
    
    public TxzAsrUdpCancel clear() {
      cachedSize = -1;
      return this;
    }
    
    @Override
    public TxzAsrUdpCancel mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
        }
      }
    }
    
    public static TxzAsrUdpCancel parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new TxzAsrUdpCancel(), data);
    }
    
    public static TxzAsrUdpCancel parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new TxzAsrUdpCancel().mergeFrom(input);
    }
  }
  
  public static final class TxzAsrUdpPullRange extends
      com.google.protobuf.nano.MessageNano {
    
    private static volatile TxzAsrUdpPullRange[] _emptyArray;
    public static TxzAsrUdpPullRange[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new TxzAsrUdpPullRange[0];
          }
        }
      }
      return _emptyArray;
    }
    
    // optional uint32 uint32_begin = 1;
    public java.lang.Integer uint32Begin;
    
    // optional uint32 uint32_end = 2;
    public java.lang.Integer uint32End;
    
    public TxzAsrUdpPullRange() {
      clear();
    }
    
    public TxzAsrUdpPullRange clear() {
      uint32Begin = null;
      uint32End = null;
      cachedSize = -1;
      return this;
    }
    
    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.uint32Begin != null) {
        output.writeUInt32(1, this.uint32Begin);
      }
      if (this.uint32End != null) {
        output.writeUInt32(2, this.uint32End);
      }
      super.writeTo(output);
    }
    
    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.uint32Begin != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(1, this.uint32Begin);
      }
      if (this.uint32End != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(2, this.uint32End);
      }
      return size;
    }
    
    @Override
    public TxzAsrUdpPullRange mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.uint32Begin = input.readUInt32();
            break;
          }
          case 16: {
            this.uint32End = input.readUInt32();
            break;
          }
        }
      }
    }
    
    public static TxzAsrUdpPullRange parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new TxzAsrUdpPullRange(), data);
    }
    
    public static TxzAsrUdpPullRange parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new TxzAsrUdpPullRange().mergeFrom(input);
    }
  }
  
  public static final class TxzAsrUdpPullPkgInfo extends
      com.google.protobuf.nano.MessageNano {
    
    private static volatile TxzAsrUdpPullPkgInfo[] _emptyArray;
    public static TxzAsrUdpPullPkgInfo[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new TxzAsrUdpPullPkgInfo[0];
          }
        }
      }
      return _emptyArray;
    }
    
    // optional uint32 uint32_pkg_id = 1;
    public java.lang.Integer uint32PkgId;
    
    // repeated .com.txz.asr.udp.TxzAsrUdpPullRange rpt_msg_frame_range = 2;
    public com.txz.asr.udp.TxzAsrUdpProtosV0.TxzAsrUdpPullRange[] rptMsgFrameRange;
    
    public TxzAsrUdpPullPkgInfo() {
      clear();
    }
    
    public TxzAsrUdpPullPkgInfo clear() {
      uint32PkgId = null;
      rptMsgFrameRange = com.txz.asr.udp.TxzAsrUdpProtosV0.TxzAsrUdpPullRange.emptyArray();
      cachedSize = -1;
      return this;
    }
    
    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.uint32PkgId != null) {
        output.writeUInt32(1, this.uint32PkgId);
      }
      if (this.rptMsgFrameRange != null && this.rptMsgFrameRange.length > 0) {
        for (int i = 0; i < this.rptMsgFrameRange.length; i++) {
          com.txz.asr.udp.TxzAsrUdpProtosV0.TxzAsrUdpPullRange element = this.rptMsgFrameRange[i];
          if (element != null) {
            output.writeMessage(2, element);
          }
        }
      }
      super.writeTo(output);
    }
    
    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.uint32PkgId != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(1, this.uint32PkgId);
      }
      if (this.rptMsgFrameRange != null && this.rptMsgFrameRange.length > 0) {
        for (int i = 0; i < this.rptMsgFrameRange.length; i++) {
          com.txz.asr.udp.TxzAsrUdpProtosV0.TxzAsrUdpPullRange element = this.rptMsgFrameRange[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(2, element);
          }
        }
      }
      return size;
    }
    
    @Override
    public TxzAsrUdpPullPkgInfo mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.uint32PkgId = input.readUInt32();
            break;
          }
          case 18: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 18);
            int i = this.rptMsgFrameRange == null ? 0 : this.rptMsgFrameRange.length;
            com.txz.asr.udp.TxzAsrUdpProtosV0.TxzAsrUdpPullRange[] newArray =
                new com.txz.asr.udp.TxzAsrUdpProtosV0.TxzAsrUdpPullRange[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.rptMsgFrameRange, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new com.txz.asr.udp.TxzAsrUdpProtosV0.TxzAsrUdpPullRange();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new com.txz.asr.udp.TxzAsrUdpProtosV0.TxzAsrUdpPullRange();
            input.readMessage(newArray[i]);
            this.rptMsgFrameRange = newArray;
            break;
          }
        }
      }
    }
    
    public static TxzAsrUdpPullPkgInfo parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new TxzAsrUdpPullPkgInfo(), data);
    }
    
    public static TxzAsrUdpPullPkgInfo parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new TxzAsrUdpPullPkgInfo().mergeFrom(input);
    }
  }
  
  public static final class TxzAsrUdpPull extends
      com.google.protobuf.nano.MessageNano {
    
    private static volatile TxzAsrUdpPull[] _emptyArray;
    public static TxzAsrUdpPull[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new TxzAsrUdpPull[0];
          }
        }
      }
      return _emptyArray;
    }
    
    // optional uint32 uint32_pkg_size = 1;
    public java.lang.Integer uint32PkgSize;
    
    // optional uint32 uint32_frame_size = 2;
    public java.lang.Integer uint32FrameSize;
    
    // repeated .com.txz.asr.udp.TxzAsrUdpPullPkgInfo rpt_msg_pkg_info = 3;
    public com.txz.asr.udp.TxzAsrUdpProtosV0.TxzAsrUdpPullPkgInfo[] rptMsgPkgInfo;
    
    // repeated .com.txz.asr.udp.TxzAsrUdpPullRange rpt_msg_pkg_id_range = 4;
    public com.txz.asr.udp.TxzAsrUdpProtosV0.TxzAsrUdpPullRange[] rptMsgPkgIdRange;
    
    public TxzAsrUdpPull() {
      clear();
    }
    
    public TxzAsrUdpPull clear() {
      uint32PkgSize = null;
      uint32FrameSize = null;
      rptMsgPkgInfo = com.txz.asr.udp.TxzAsrUdpProtosV0.TxzAsrUdpPullPkgInfo.emptyArray();
      rptMsgPkgIdRange = com.txz.asr.udp.TxzAsrUdpProtosV0.TxzAsrUdpPullRange.emptyArray();
      cachedSize = -1;
      return this;
    }
    
    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.uint32PkgSize != null) {
        output.writeUInt32(1, this.uint32PkgSize);
      }
      if (this.uint32FrameSize != null) {
        output.writeUInt32(2, this.uint32FrameSize);
      }
      if (this.rptMsgPkgInfo != null && this.rptMsgPkgInfo.length > 0) {
        for (int i = 0; i < this.rptMsgPkgInfo.length; i++) {
          com.txz.asr.udp.TxzAsrUdpProtosV0.TxzAsrUdpPullPkgInfo element = this.rptMsgPkgInfo[i];
          if (element != null) {
            output.writeMessage(3, element);
          }
        }
      }
      if (this.rptMsgPkgIdRange != null && this.rptMsgPkgIdRange.length > 0) {
        for (int i = 0; i < this.rptMsgPkgIdRange.length; i++) {
          com.txz.asr.udp.TxzAsrUdpProtosV0.TxzAsrUdpPullRange element = this.rptMsgPkgIdRange[i];
          if (element != null) {
            output.writeMessage(4, element);
          }
        }
      }
      super.writeTo(output);
    }
    
    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.uint32PkgSize != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(1, this.uint32PkgSize);
      }
      if (this.uint32FrameSize != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(2, this.uint32FrameSize);
      }
      if (this.rptMsgPkgInfo != null && this.rptMsgPkgInfo.length > 0) {
        for (int i = 0; i < this.rptMsgPkgInfo.length; i++) {
          com.txz.asr.udp.TxzAsrUdpProtosV0.TxzAsrUdpPullPkgInfo element = this.rptMsgPkgInfo[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(3, element);
          }
        }
      }
      if (this.rptMsgPkgIdRange != null && this.rptMsgPkgIdRange.length > 0) {
        for (int i = 0; i < this.rptMsgPkgIdRange.length; i++) {
          com.txz.asr.udp.TxzAsrUdpProtosV0.TxzAsrUdpPullRange element = this.rptMsgPkgIdRange[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(4, element);
          }
        }
      }
      return size;
    }
    
    @Override
    public TxzAsrUdpPull mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.uint32PkgSize = input.readUInt32();
            break;
          }
          case 16: {
            this.uint32FrameSize = input.readUInt32();
            break;
          }
          case 26: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 26);
            int i = this.rptMsgPkgInfo == null ? 0 : this.rptMsgPkgInfo.length;
            com.txz.asr.udp.TxzAsrUdpProtosV0.TxzAsrUdpPullPkgInfo[] newArray =
                new com.txz.asr.udp.TxzAsrUdpProtosV0.TxzAsrUdpPullPkgInfo[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.rptMsgPkgInfo, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new com.txz.asr.udp.TxzAsrUdpProtosV0.TxzAsrUdpPullPkgInfo();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new com.txz.asr.udp.TxzAsrUdpProtosV0.TxzAsrUdpPullPkgInfo();
            input.readMessage(newArray[i]);
            this.rptMsgPkgInfo = newArray;
            break;
          }
          case 34: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 34);
            int i = this.rptMsgPkgIdRange == null ? 0 : this.rptMsgPkgIdRange.length;
            com.txz.asr.udp.TxzAsrUdpProtosV0.TxzAsrUdpPullRange[] newArray =
                new com.txz.asr.udp.TxzAsrUdpProtosV0.TxzAsrUdpPullRange[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.rptMsgPkgIdRange, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new com.txz.asr.udp.TxzAsrUdpProtosV0.TxzAsrUdpPullRange();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new com.txz.asr.udp.TxzAsrUdpProtosV0.TxzAsrUdpPullRange();
            input.readMessage(newArray[i]);
            this.rptMsgPkgIdRange = newArray;
            break;
          }
        }
      }
    }
    
    public static TxzAsrUdpPull parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new TxzAsrUdpPull(), data);
    }
    
    public static TxzAsrUdpPull parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new TxzAsrUdpPull().mergeFrom(input);
    }
  }
  
  public static final class TxzAsrUdpClean extends
      com.google.protobuf.nano.MessageNano {
    
    private static volatile TxzAsrUdpClean[] _emptyArray;
    public static TxzAsrUdpClean[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new TxzAsrUdpClean[0];
          }
        }
      }
      return _emptyArray;
    }
    
    // optional uint32 uint32_last_pkg_id = 1;
    public java.lang.Integer uint32LastPkgId;
    
    public TxzAsrUdpClean() {
      clear();
    }
    
    public TxzAsrUdpClean clear() {
      uint32LastPkgId = null;
      cachedSize = -1;
      return this;
    }
    
    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.uint32LastPkgId != null) {
        output.writeUInt32(1, this.uint32LastPkgId);
      }
      super.writeTo(output);
    }
    
    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.uint32LastPkgId != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(1, this.uint32LastPkgId);
      }
      return size;
    }
    
    @Override
    public TxzAsrUdpClean mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.uint32LastPkgId = input.readUInt32();
            break;
          }
        }
      }
    }
    
    public static TxzAsrUdpClean parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new TxzAsrUdpClean(), data);
    }
    
    public static TxzAsrUdpClean parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new TxzAsrUdpClean().mergeFrom(input);
    }
  }
  
  public static final class TxzAsrUdpResultData extends
      com.google.protobuf.nano.MessageNano {
    
    private static volatile TxzAsrUdpResultData[] _emptyArray;
    public static TxzAsrUdpResultData[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new TxzAsrUdpResultData[0];
          }
        }
      }
      return _emptyArray;
    }
    
    // optional bool bool_last = 1;
    public java.lang.Boolean boolLast;
    
    // optional uint32 uint32_compress_type = 2;
    public java.lang.Integer uint32CompressType;
    
    // optional bytes str_data = 3;
    public byte[] strData;
    
    public TxzAsrUdpResultData() {
      clear();
    }
    
    public TxzAsrUdpResultData clear() {
      boolLast = null;
      uint32CompressType = null;
      strData = null;
      cachedSize = -1;
      return this;
    }
    
    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.boolLast != null) {
        output.writeBool(1, this.boolLast);
      }
      if (this.uint32CompressType != null) {
        output.writeUInt32(2, this.uint32CompressType);
      }
      if (this.strData != null) {
        output.writeBytes(3, this.strData);
      }
      super.writeTo(output);
    }
    
    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.boolLast != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(1, this.boolLast);
      }
      if (this.uint32CompressType != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(2, this.uint32CompressType);
      }
      if (this.strData != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBytesSize(3, this.strData);
      }
      return size;
    }
    
    @Override
    public TxzAsrUdpResultData mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.boolLast = input.readBool();
            break;
          }
          case 16: {
            this.uint32CompressType = input.readUInt32();
            break;
          }
          case 26: {
            this.strData = input.readBytes();
            break;
          }
        }
      }
    }
    
    public static TxzAsrUdpResultData parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new TxzAsrUdpResultData(), data);
    }
    
    public static TxzAsrUdpResultData parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new TxzAsrUdpResultData().mergeFrom(input);
    }
  }
  
  public static final class TxzAsrUdpResult extends
      com.google.protobuf.nano.MessageNano {
    
    private static volatile TxzAsrUdpResult[] _emptyArray;
    public static TxzAsrUdpResult[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new TxzAsrUdpResult[0];
          }
        }
      }
      return _emptyArray;
    }
    
    // optional uint32 uint32_pkg_id = 1;
    public java.lang.Integer uint32PkgId;
    
    // optional uint32 uint32_frame_info = 2;
    public java.lang.Integer uint32FrameInfo;
    
    // optional bytes str_frame_data = 3;
    public byte[] strFrameData;
    
    public TxzAsrUdpResult() {
      clear();
    }
    
    public TxzAsrUdpResult clear() {
      uint32PkgId = null;
      uint32FrameInfo = null;
      strFrameData = null;
      cachedSize = -1;
      return this;
    }
    
    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.uint32PkgId != null) {
        output.writeUInt32(1, this.uint32PkgId);
      }
      if (this.uint32FrameInfo != null) {
        output.writeUInt32(2, this.uint32FrameInfo);
      }
      if (this.strFrameData != null) {
        output.writeBytes(3, this.strFrameData);
      }
      super.writeTo(output);
    }
    
    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.uint32PkgId != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(1, this.uint32PkgId);
      }
      if (this.uint32FrameInfo != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(2, this.uint32FrameInfo);
      }
      if (this.strFrameData != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBytesSize(3, this.strFrameData);
      }
      return size;
    }
    
    @Override
    public TxzAsrUdpResult mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.uint32PkgId = input.readUInt32();
            break;
          }
          case 16: {
            this.uint32FrameInfo = input.readUInt32();
            break;
          }
          case 26: {
            this.strFrameData = input.readBytes();
            break;
          }
        }
      }
    }
    
    public static TxzAsrUdpResult parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new TxzAsrUdpResult(), data);
    }
    
    public static TxzAsrUdpResult parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new TxzAsrUdpResult().mergeFrom(input);
    }
  }
}
